bbatsov/projectile

projectile.el
=> Fix pasto in last change to projectile-version

projectile.el
More entry points here to projectile. Not sure what your opinions or standards are about when to set an autoload or not.
=> Autoloads for some projectile-find-file defuns

README.md
See also
- https://help.github.com/articles/relative-links-in-readmes/
=> Relative path is better than absolute path

helm-projectile.el
Instead, only build Helm dwim source when applicable. That is, when the
number of candidates are greater than 1 or no candidate found and the
whole project files are displayed as usual projectile-find-file.
This change also replaces static Helm source with dynamically generated
helm DWIM source. In the future, Helm sources should be changed like
this to adapt to user settings easily. Currently, user has to set fuzzy
matching before loading Helm Projectile, which is inconvenient.
=> [Fix #672] Don't quit when build Helm source

projectile.el
* projectile.el (projectile-completing-read): Update.
=> Use `ivy-completing-read' instead of `ivy-read'

projectile.el
Fixes https://github.com/syl20bnr/spacemacs/issues/1256
=> When cache cleared, user expects no old files

README.md
Hey! Just saw these ones in passing, awesome docs man!
=> A couple of edits in the README

CHANGELOG.md, helm-projectile.el
=> Remove current buffer from helm-source-projectile-buffer

projectile.el
According to issue #757 I have implemented support for [Midje](https://github.com/marick/Midje) here.
I apologize but I am not a proper elisp expert...I am ready for the bashing :smile:
=> General test functions improvements + add midje support

projectile.el
Also changed the order of two functions to match the var declaration alphabetical order.
=> Use --some instead of --reduce-from and improve some docs

CHANGELOG.md, projectile.el
fixes #625 and possibly others (#740 ?).
=> made projectile ignore ignored files on windows

projectile.el
fix the issue https://github.com/bbatsov/projectile/issues/778
=> projectile-dir-files-external fix for frozen windows emacs

projectile.el
=> [Fix #695] Detect find -readable support

helm-projectile.el
=> Store helm marked files before calling completing-read

Cask, projectile.el
And i refactor `helm-projectile-ag` with same ignore list.
Upd: I update pull request. Make more simplest. Just fix `projectile-ag` for ignoring configured paths.
And i add auto-requiring of "ag" package.
=> [Fix #855] Ignore files and directories in projectile-ag

helm-projectile.el
This is related to #914.
CC: @edurante
=> Correct history variable name

CHANGELOG.md, projectile.el
Could somebody who uses ggtags please test this? I'm guessing the behaviour there.
=> support etags-select close #910 and #683 #668 #557 #699

projectile.el
When working with multiple projects, I find it useful to have different shells for each project. This patch adds a command to launch shell in current root directory.
The shell buffer will be called `*shell project-name*`.
=> Add a command to run shell in project's root directory

projectile.el
=> Fix projectile-skel-dir-locals

CHANGELOG.md, projectile.el
- [-] You've added tests (if possible) to cover your change(s) [does not seem necessary]
- [-] You've updated the readme (if adding/changing user-visible functionality) [does not seem noteworthy]
=> Specify --with-keep.source when installing R projects

CHANGELOG.md, projectile.el
Thanks!
Racket projects typically contain a file "info.rkt" in the root. The
standard command to test a Racket project is "raco test .".
=> Add support for Racket projects

CHANGELOG.md, projectile.el
Makes possible to alternate between the test and the implementation files.
=> Register elixir project type

README.md
I added a link to [counsel-projectile](https://github.com/ericdanan/counsel-projectile) to the README in the appropriate section. 
Thanks!
=> Add link to counsel-projectile in README

CHANGELOG.md, projectile.el
See #1063 for the problems I faced using Projectile in a Windows Fossil repository and the commit messages below for my thought process re: fixes.
=> Fix Fossil support on Windows.

projectile.el
=> Show correct project name when switching projects

projectile.el
=> Handle prefix argument to projectile-multi-occur as context lines

projectile.el
Need to ignore current cached project when iterating across all projects
See https://github.com/bbatsov/projectile/pull/1149#issuecomment-321337673
=> Fix `(projectile-all-project-files)`

CHANGELOG.md, projectile.el
Modify Ruby and Elixir project settings.
Thanks!
=> Modify Ruby and Elixir project settings

CHANGELOG.md, projectile.el
Register the angular project type
Thanks!
=> Add angular project type

CHANGELOG.md, projectile.el
=> Register project type for Crystal

CHANGELOG.md, projectile.el
=> Add default `test-suffix` to `npm` project

projectile.el
=> Doc string typo fix

projectile.el, test/projectile-test.el
=> [Fix #1299] Support `nil` for `projectile-git-submodule-command`

test/projectile-legacy-test.el, test/projectile-test.el
Migrate ert tests for `projectile-load-known-projects` and `projectile-merge-known-projects`.
Thanks!
=> migrate tests for load-known-projects and merge-known-projects

projectile.el, test/projectile-test.el
=>  Migrate `projectile-test-ignored-directory-p' to buttercup 

CHANGELOG.md, doc/usage.md, projectile.el
Add commands to switch to previous / next buffers in the current project.
Fix #896.
=> Previous / next project buffer commands

projectile.el
=> fix for projectile-project-files relative path bug

projectile.el
This PR contains various small fixes. I think the commit messages should explain the rationale for each change but let me know if there are any questions.
I couldn't run `make test` because I don't have cask.
=> Various small fixes

projectile.el
@bbatsov oops :sweat_smile: 
Thanks to @mookid for noticing!
=> Fix bug in compilation-find-file-projectile-find-compilation-buffer

projectile.el
Adds a `:run` command to Rust projects (`cargo run`).
- [N/A] You've added tests (if possible) to cover your change(s)
- [N/A] You've updated the changelog (if adding/changing user-visible functionality)
- [N/A] You've updated the readme (if adding/changing user-visible functionality)
Thanks!
=> Add run command for rust-cargo projects

projectile.el
Closes #1385.
Updates `projectile-replace` for Emacs 27.
=> Update projectile-replace for Emacs 27

doc/configuration.md
Closes https://github.com/bbatsov/projectile/issues/1395
=> [Fix #1395] Fix typo in documentation.

projectile.el
This test configuration will by default run _all_ tests for Bloop/SBT projects which follow the standard idioms.
Thanks!
=> Update Bloop Test Configuration

doc/usage.md
I wasn't able to locate this info in the docs, so I hope this is helpful.
Thanks!
=> Document prefix arg on ag.el

projectile.el
=> Properly filter by file type when using fd

CHANGELOG.md, projectile.el
=> Fix #1432 to support .NET project

projectile.el
This PR allows projectile to detect python projects based on the presence of a `pyproject.toml` file.
Python projects are already detected using the `setup.py` file.
However, some workflows (for example using `[poetry](https://poetry.eustace.io/)`) doesn't require a `setup.py` file but only a `pyproject.toml`.
This ensures those project are detected properly by projectile.
Thanks!
=> Add python project file to root discovery

projectile.el
Hi!
These very minor updates follow the [style guide](https://github.com/bbatsov/emacs-lisp-style-guide).
=> Add sharp-quotes; remove quoted lambda

CHANGELOG.md, projectile.el
Hello,
This will close #1471
Here's my checklist before merging:
=> Add projectile-run-vterm

projectile.el
Pretty much self explanatory :-)
The only thing I'm not sure is about the "emacs27" strings, what should I use?
Thanks!
=> Fix Emacs 27 warnings

projectile.el
Add a run command for cabal projects
=> Add a run command for cabal projects.

projectile.el
=> Add OCaml extensions to projectile-other-file-alist

projectile.el
From
https://github.com/ocaml/tuareg/blob/ccde45bbc292123ec20617f1af7f7e19f7481545/tuareg.el#L240
----
#
=> Add more OCaml extensions to projectile-other-file-alist

CHANGELOG.md, doc/modules/ROOT/pages/projects.adoc, projectile.el
Hi! This PR adds support for scala [Mill](http://www.lihaoyi.com/mill/) projects.
Thanks!
=> Add support for scala mill projects.

projectile.el
=> Silence Emacs 27's byte-compiler

doc/modules/ROOT/pages/installation.adoc
=> [Docs] mode binds for use-package

CHANGELOG.md, README.md, doc/modules/ROOT/pages/configuration.adoc, doc/modules/ROOT/pages/index.adoc, projectile.el
@bbatsov Regarding the discussion in https://github.com/raxod502/selectrum/issues/233 - would auto-detection of the completion system like this work too for you? I haven't checked the necessary boxes here, but if there is interest, I will proceed. Maybe there is a reason why you didn't implement auto-detection right away, while you have it for the tags backend.
Thanks!
=> completion system auto-detection

projectile.el
hopefully fixes #1625 and #1624 
Thanks!
=> projectile-files-via-ext-command: avoid touching users' windows

doc/modules/ROOT/pages/projects.adoc
Hi! This PR just fixes some minor typos in the doc for `related-files-fn`.
Thanks!
=> Fix Typos in related-files-fn doc

projectile.el
let tag generation be aware of ignore pattern.
Thanks!
=> [Fix #705] let tag generation be aware of ignore pattern.

CHANGELOG.md, projectile.el
Fix #1511 
Support https://github.com/dajva/rg.el
Thanks!
=> projectile-ripgrep: support rg.el package

projectile.el
Minor fixes to remove byte compilation warnings on projectile.el
=> fix byte compilation warnings

projectile.el
I came up with this simplification while working on #1732 yesterday.
Thanks!
=> Minor list processing cleanup

index.md
Grammar fix
This is a small change to fix the grammar in the github pages website, no main-branch code has been changed.
=> [gh-pages] Update index.md

CHANGELOG.md, projectile.el
=> [Fix #1750] Fix src-dir and test-dir for Maven projects

projectile.el
=> Add vterm to the menu

CHANGELOG.md, projectile.el
This pull request adds support for the Pijul VCS.
=> Adding some Pijul support

projectile.el
Fix some minor checkdoc warnings.
=> Fix some minor checkdoc warnings.

doc/modules/ROOT/pages/projects.adoc
Fix minor space typo in projects.adoc.
Thanks!
=> Fix projects.adoc typo

projectile.el
https://github.com/bbatsov/projectile/pull/1747 wasn't working properly. 
Not sure I should update the changelog again?
Thanks!
=> Fix support for preset-based installs in CMake projects.

CHANGELOG.md, doc/modules/ROOT/pages/projects.adoc, projectile.el, test/projectile-test.el
Discovered using codespell:
https://github.com/codespell-project/codespell
=> Fix several typos and spelling errors
