bbatsov/projectile

- README.md
- helm-projectile.el
To disable it, simply set helm-projectile-fuzzy-match to nil before
loading helm-projectile.
> Allow to disable fuzzy matching in Helm Projectile

- helm-projectile.el
Currently, the sources can only be used in a project recognized by
Projectile. It cannot be composed to be used with other commands like
helm-for-files. This change supports such use case without compromise
the consistency of Projectile: Helm Projectile commands are responsible
for throwing the same errors as stock Projectile, but not the source.
> Enable helm projectile sources reusable

- helm-projectile.el
Inserting file into new Dired buffer fails if the inserting file is an
empty string. Check to make sure no empty string is in the file list.
Also remove duplicate `C-c f` binding that shadows the command that
creates virtual Dired buffer.
> Fix a bug in creating new virtual dir

- helm-projectile.el
Using (projectile-project-root), helm-projectile-grep breaks on Windows
because GNU Grep requires Unix path, while the call returns Windows
path. Fix it by using current directory and use default-directory to set
grep location.
Also make helm-projectile-grep works with Grep 2.5.4 (BSD) on Mac OS X.
> [Fix #537] Correct command line arguments

- helm-projectile.el
Here is an updated patch with suggested change.
Please ignore this, if this pull request is redundant.
I'm still learning how to use github properly.
> Use '-filter' rather than 'filter', and use 'string=' rather than 'string-empty-p'

- projectile.el
If a user visits a project using Dired, the project won't be recorded
into project list because no projectile-cache-projects-find-file-hook is
executed. The hook must be added to dired-before-readin-hook that runs
before Dired does anything else.
> Fix: Projectile cannot remember projects

- projectile.el
If magit package is not yet loaded, `projectile` cannot find `magit-status-internal` because that function is not auto-loaded. `magit-status-internal` is now an alias for `magit-status`,  so `magit-status` should be used instead.
> Use `magit-status` instead of `magit-status-internal`

- projectile.el
It should be able to handle relative paths that point to file in a
project. For example, we have file custom/setup-a.el, and file
personal/setup-b.el contains ../custom/setup-a.el,
projectile-find-file-dwim should be able to jump to it.
> Make projectile-find-file-dwim handle relative path

- helm-projectile.el
Document that this variable needs to be set before helm-projectile is
loaded.  (Fixes bug#634)
> Improve helm-projectile-fuzzy-match docstring

- helm-projectile.el
Hi Bozhidar,
This PR fixes the missing dependency on dash for helm-projectile.el.
Cheers,
syl20bnr
> Missing dependency on dash for helm-projectile.el

- projectile.el
"Lighter" was misspelled as "ligher" in the docstring for `projectile-mode-line`.
> Fix docstring typo

- CHANGELOG.md
- projectile.el
Just like it says in the title! :sparkles:
> Fix `projectile-regenerate-tags` in dirs with spaces

- helm-projectile.el
- persp-projectile.el
Hopefully answers #586, basically uses @rsenna fix with some cleaning.
@tuhdo My additions should be helm-safe in the sense that helm lets you find stuff in new frames and the functionality added is aware of that and should hopefully do the right thing. Btw, I'm guessing that the `projectile-persp-bridge' macro while smart is not make-frame safe, although I'm not sure.
@bbatsov You probably just need the last two commits, my git-foo is so poor I don't know how to squash commits that you already have merged. Sorry about that.
> Persp projectile

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Add a new defcustom projectile-globally-ignored-file-extensions that is
used by projectile-remove-ignored to remove files based off of the file
suffix.
> [Fix #560] [Fix #580] Add new defcustom that is used for globally ignoring files by extension

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
In projects where there are multiple file names with the same
header/source combinations we can still provide more accurate results by
sorting the candidates list to put the other-file under the same
directory name as this file to the top of the list.
So now if we have a directory tree like this:
```
|-src-
|
moduleA-
|
filename.c
moduleB-
|
filename.c
|-include-
|
moduleA-
|
filename.h
moduleB-
|
filename.h
```
`projectile-find-other-file` will always return the proper other file and there is no need to check the return list and choose which one it is that you actually wanted.
I tested this in the projects I am working on and it seems to work perfectly.
Note: In the sorting of the list the `other-file` is not used and as such there is a warning when you byte compile. So I suppose there …
> projectile-find-other-file sort candidates

- projectile.el
- test/projectile-test.el
Previously, command line that was being generated was this:
ctags -Re -f TAGS "--exclude=<pattern> .... "
Due to the inclusion of quotes, the exclude pattern is completely
ignored by ctags.
This commit fixes this issue and generates the command line as follows:
ctags -Re -f TAGS --exclude="<pattern>" ...
This does not break the exclude option while still works with spaces in
filenames.
> Fix generation of command for tag generation

- helm-projectile.el
Also give back helm-projectile-ack a key binding.
> [Fix #678] Allow helm-projectile-ack search recursively

- projectile.el
`-L` (capital L) shows NON-matching files `-l` is what we want: matching ones. This is true for grep and git-grep .
> fix inversion in projectile-files-with-string

- CHANGELOG.md
- projectile.el
A small patch to add a spinning progress reporter to the native indexing method.
> Add a progress reporter to the native indexing method

- helm-projectile.el
let `helm-projectile-ag` use prefix argument to ask for options dynamically.  #598  for details.
> Support `ag` ask for options dynamically

- projectile.el
* projectile.el (projectile-completion-system): Update.
(projectile-completing-read): Update.
> Add ivy to `projectile-completion-system'

- projectile.el
* projectile.el (projectile-completing-read): Update.
`cl-delete-duplicates' for thousands of candidates is just too slow.
Anyway, the choices are supposed to be unique in the first place.
> Remove the uniqueness enforcement for `ivy-read'

- projectile.el
This adds support for compiling (installing) and testing (checking) R (http://r-project.org/) packages as projectile projects.
> add R package project type

- projectile.el
In the current version of projectile (0.11.0) and helm-mode (1.6.4), explicitly passing a directory into `projectile-replace` results in the following error:
Opening input file: no such file or directory, /path/to/directorypath/to/file.el
Specifically, a `/` is missing between `/path/to/directory` and `path/to/file.el` because `helm-mode`'s directory selection strips the trailing slash before returning it. This patch makes `projectile-replace` robust against these edge cases.
> Fix `projectile-replace` directory selection with `helm-mode`

- persp-projectile.el
Perspective should only be changed if user is actually in a project directory.
> Fix perspective switching behavior

- projectile.el
projectile.el (projectile-completing-read): Update the call to
`ivy-read'
> Update the call to `ivy-read'

- CHANGELOG.md
- projectile.el
Set `default-directory` before reading the compilation command so that
`completion-at-point` offers appropriate targets even when
`projectile-compile-project` is called from a subdirectory.  Also,
remove unnecessary check on DIR argument.
> Set default-directory before compilation command

- helm-projectile.el
`helm-projectile-ag` would search through all my directories and give me too much stuff to be useful, fixed with this PR. (`projectile-ignored-directories-rel` also contains the `projectile-globally-ignored-files` so it just adds the folders in your `.projectile` file)
> made helm-projectile-ag ignore files and folders from .projectile

- helm-projectile.el
It's entirely redundant here, and we should not force a given set of preferences upon the user.
> Don't require helm-config

- projectile.el
Tox [0] is a tool that allows running tests in multiple Python
environments sequentially. This is especially useful when working on
projects supporting both Python 2 and 3 because the standard unittest
runner can only run against one Python version at a time.
[0] https://testrun.org/tox/latest/
> Add support for the tox testing automation tool

- helm-projectile.el
If invoked outside of a project, helm-projectile only shows a list of
projects. Currently, helm-projectile-sources-list includes project
roots, project buffer and project file listings, but empty when used
outside of a project effectively shows only project listing.
> Simplify helm-projectile command

- projectile.el
Currently, Projectile shows any directory it's in. This is not useful
since we don't know whether or not we are in a project directory. This
change makes it only shows project root in modeline when we are actually
in a project, so we know whether we are in a Project or not when
entering a buffer, and also save screen estate.
> Don't show Projectile directory when not in project

- helm-projectile.el
We need to remove the initial buffer before Helm uses populate the
buffer list in its own buffer, not after.
> Properly remove initial buffer

- helm-projectile.el
Similar to other sources, simply returns nil when not in a project, so
it can be used with other Helm commands. For explicity
helm-projectile-switch-to-buffer, the default error is still signaled.
> [Fix #743] Allow buffer source to be composable

- projectile.el
`projectile-compile-project` now respects the value of
`compilation-ask-about-save` just like `M-x compile` does, with the
exception that only buffers from the current project are considered for
saving.
> Align projectile-compile-project even more closely with M-x compile

- projectile.el
The default value of `projectile-globally-ignored-directories` (defined [here](https://github.com/bbatsov/projectile/blob/c0dcf03239dbc3d1c5307ff720cce3879984299e/projectile.el#L267)) is a list whose first element is ".idea". However, when you run `projectile-grep` you can see all the elements of the list being ignored except for ".idea".
If you do `(add-to-list 'projectile-globally-ignored-directories ".ensime_cache")` then ".ensime_cache" is added to the front of the list. Now, you can see that the `projectile-grep` passes ".idea" to find as one of the directories to skip but not ".ensime_cache".
This happens because the exception list is constructed in `projectile-ignored-directories` by appending `projectile-globally-ignored-directories` and `(projectile-project-ignored-directories)` …
> The first element of projectile-globally-ignored-directories is not used for grep

- helm-projectile.el
So far only the globally ignored files/directories have been used
while the grep command uses also the ignored files/directories
defined in `.projectile`
This should fix #766. Seem like I was wrong and only the helm-ack command is affected.
> Use project ignored files for helm-projectile-ack

- projectile.el
- test/projectile-test.el
I have no  global picture so feel free to close if it's nonsense.
`file-truename` is very slow on remotes because it has to check if each subdir is a simlink.  I think inner `file-truename` is not needed because you don't care what you use as key in your cache as long that key stays the same, right?  Outer `file-truename` is not needed either. It's the task of the  cacher to store the truename. Also, if you pass a truename to the `root-function` you need not truename it afterwards because guaranties to produce truename if it gets truename.
> [Fix #657] Remove `file-truename` calls from `projectile-project-root`

- helm-projectile.el
`helm-ag` supports more than just `ag` (as outlined in the docs [here](https://github.com/syohex/emacs-helm-ag#helm-agel-with-the-platinum-searcher-or-ack)). Having this check in breaks code such as:
```
(let ((helm-ag-base-command "pt -e --nocolor --nogroup"))
(call-interactively 'helm-projectile-ag))
```
unless you happen to have ag present (when it's not needed).
> removed check for executable

- helm-projectile.el
To make it possible to use `helm-source-projectile-buffers-list` and `helm-source-buffers-list` at the same time, for example:
```elisp
(defun foo ()
(interactive)
(helm :sources '(helm-source-projectile-buffers-list
helm-source-buffers-list)))
```
> [Fix #750] Avoid helm source conflict

- CHANGELOG.md
- projectile.el
This allows to dynamically decide if a project should be added to `projectile-known-projects` or not. For example, it provides a way to ignore all remote projects or all projects in a certain directory.
> Add new option projectile-ignored-project-function

- helm-projectile.el
I forgot to wrap projectile-ignored-files/directories in parenthesis to actually call the functions.
see #767
> fix helm-projectile-ack

- projectile.el
Specifically in projectile-ignored-project-function and
projectile-ignored-project-p:
- Fix quotes around symbols to conform to standard emacs docstring
convention.
- Spell the name of file-remote-p correctly.
> Fix markup in docstrings

- helm-projectile.el
Previously, this map was defined anonymously inside the Helm source. Defining it separately allows users to further customize the map if desired.
> Define helm-projectile-projects-map

- helm-projectile.el
Recent changes in Helm (f71ce5e) broke the `helm-projectile-hack-actions`. This commit addresses the incompatible issue introduced by Helm f71ce5e.
> helm-projectile.el: compatible with the latest Helm

- helm-projectile.el
Helm change 6cd108f moved types to helm-types.el. Require this in
the way expected by helm.
Fixes bbatsov/projectile#797
> helm-projectile.el: make compatible with Helm refactoring

- helm-projectile.el
Since helm-ff-mode-line-string no longer exists and is replaced with
helm-read-file-name-mode-line-string.
> Replace helm-ff-mode-line-string

- helm-projectile.el
It would appear there was a mass-deprecation of helm's mode-line settings in emacs-helm/helm@b95e5b049381b953c2d203eb39486344cc7165cd.  `helm-projectile.el` needs to remove those references or it breaks; I specifically witnessed the issue with the `helm-grep-mode-line-string`, and then did a little inspection to find the reference to `helm-buffer-mode-line-string`, which appears to also be removed in the referenced commit.
> Remove a couple of mode-line references from helm-projectile

- projectile.el
Change projectile-generic-command so that it prunes unreadable files and
prevents projectile from seeing them.
> Fix #695 'If ignored directory doesn't have proper permissions, projectile-find-file displays "find: 'foldername': permission denied"' (again)

- projectile.el
1. Don't invoke shell by calling call-process instead of shell-command
2. Don't output error message when 'find' does not support '-readable' option
`1.` improves performance. https://github.com/bbatsov/projectile/pull/811#issuecomment-124335174 (CC: @xuchunyang). (Your benchmark result on my machine. Original: `0.007559`, This version: `0.002801`)
`2.` resolved https://github.com/bbatsov/projectile/pull/811#issuecomment-124343190(CC: @bixuanzju)
> Improve projectile--detect-find-command

- projectile.el
When a user invokes Projectile on a non-project directory, such
directory is cached as 'no-project-root in projectile-project-root-cache,
and the second time when such directory is added with a .projectile file
or anything that Projectile can recognize as a project, it will never
become a project because the cache always suggests Projectile such
directory is not a project. This is a mistake. We should only cache
projects, not non-projects.
> [Fix #521] Don't add non-projects to project cache

- projectile.el
Here's the suggested simplification. Sorry for causing this to get out of hand.
> [Fix #695] Use -perm for generic command

- projectile.el
POSIX does not specify the behaviour of `-perm +mode` as used with
`-perm +444`. This was a GNU extension that was deprecated on
2005-06-07 [1] and finally removed on 2013-04-21 [2].
Use the suggested replacement of `-perm /mode` instead.
[1] http://git.savannah.gnu.org/cgit/findutils.git/commit/?id=de2a4f4dd1c2e375eaea97386032f2e6720e3008
[2] http://git.savannah.gnu.org/cgit/findutils.git/commit/?id=90f0c5d24153ad3327edd6f2249fc95a5cfb72e0
> Avoid using `find -perm +mode`

- helm-projectile.el
The two variables are renamed in Helm, so we must change those in Helm
Projectile to make it work properly.
> Update helm variables

- helm-projectile.el
It's similar to how projectile-grep is doing. Otherwise, we get void
variables that are only available when grep is loaded. Also, account for
helm-grep-ignored-files/directories when searching.
> Load grep when running helm-projectile-grep/ack

- helm-projectile.el
This is to import `grep` globally in helm-projectile, otherwise `helm-projectile-ag` would fail due to `grep-find-ignored-files` being void. See #830 for more details. I could've included `(require 'grep)` under `helm-projectile-ag` separately, but I see no harm importing it globally. 
This PR is to address #830.
Thanks!
> Fix #830 (helm-projectile-ag issue)

- helm-projectile.el
> Don't require root in helm-projectile-find-file-in-known-projects

- helm-projectile.el
`helm-projectile-coerce-file' uses project root to expand file names, so
it will fail when not under a project.  It is also redundant since the
file names have been expanded when collecting them.
Continue fixing #831
> Don't expand file names in *-files-in-all-projects-list source

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
This makes overriding the "query the user" part easier.
This is pull request #616 rebased onto current master.
> Allow specifying regexp to projectile-grep

- projectile.el
Hey, 
this patch adds: 
* `stack.yaml` indicates project root
* Ignore `.stack-work` directory
* New project type `haskell-stack`
I hope I didn't miss something.
> Add support for Haskells stack tool

- CHANGELOG.md
- helm-projectile.el
If projectile-use-git-grep set to a non-nil then helm-projectile-grep will
use git-grep in git projects, otherwise fall back to regular grep.
This patch fixes #763
> Honor projectile-use-git-grep in helm-projectile-grep

- CHANGELOG.md
- helm-projectile.el
This patch allows user to use helm-projectile-grep with all its
features (like ignored files and git-grep) during selecting project. 
The only downside of this patch is that user loses ability to run a
non-recursive grep.
> Use help-projectile-grep instead of helm-find-file when selecting a project

- CHANGELOG.md
- projectile.el
VC handling of Mercurial repos is quite poor. I much prefer "Monky" https://github.com/ananthakumaran/monky
Arguably, the best solution would be to allow users to customize `projectile-vc`, instead of having special cases for "magit", "monky" or the like.
> Optionally run monky on Mercurial projects

- CHANGELOG.md
- projectile.el
Add hook right before `switch-project-action` is called.
This is related to the discussion at https://github.com/milkypostman/melpa/pull/3177
> Add projectile-before-switch-project-hook

- CHANGELOG.md
- projectile.el
I'm new to projectile so I feel like this PR may be naive; please close if so! I couldn't understand why `projectile-switch-to-buffer` was offering the current buffer as a choice. This PR excludes it, thus giving similar behavior to core emacs' `read-buffer-to-switch ` for which the docstring says:
```
...
This function is intended for the `switch-to-buffer' family of
commands since these need to omit the name of the current buffer
from the list of completions and default values."
```
> Omit current buffer from switch-to-buffer choices

- CHANGELOG.md
- projectile.el
Rename `projectile-switch-project-hook` to `projectile-after-switch-project-hook`. 
This is related to PR https://github.com/bbatsov/projectile/pull/879 which adds a `projectile-before-switch-project-hook`.
> Rename projectile-switch-project-hook to projectile-after-switch-project-hook

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Fixed parsing non-ascii characters in dirconfig (for example ignored directories in `.projectile`). I noticed that when ignoring directories with names like `harjoitustyö.prv` in `.projectile` they were being mangled by `projectile-parse-dirconfig-file` (read as `harjoitusty\303\266.prv`) and as a result weren't actually ignored. Same happens with other non-ascii characters like é.
Not sure if this is the smartest way to fix it.
Some reference material I went through:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-04/msg00331.html
https://lists.gnu.org/archive/html/emacs-diffs/2015-04/msg00308.html
> fix non-ascii char parsing in dirconfig

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Other than the project root dir.
Fixes #874.
I added a test because there was some weird behavior with trailing slashes on the directory variable (fixed with `filename-as-directory`).
> Allow specification of a compilation dir

- helm-projectile.el
The latest update broke helm-projectile-ack. This should restore functionality.
I don't see where the dir argument is used in the grep scenario, so not sure that works here.
> Fix issue with ack vs. grep in last update

- CHANGELOG.md
- projectile.el
If there is a region selected, calling ```projectile-ag``` should use region content as a search term instead of symbol at point.
> Respect selected region in projectile-ag

- CHANGELOG.md
- projectile.el
I struggled for hours, but couldn't find a way to squash the commits across the merge (which I had to do to modify the changelog). Any rebasing destroys the merge. Tried using --preserve-merges, but that does not work with interactive reordering (necessary to squash). Hopefully this is acceptable, or you can offer some advice.
> Add support for gradlew

- projectile.el
In my previous pull request I forgot to include build.boot in projectile-project-root files so I am fixing this omission.
Let me know if I should update CHANGELOG with this change.
> Add build.boot to projectile-project-root-files

- Makefile
Add a new byte-compile-strict command to Makefile which byte-compiles
`projectile.el` and `helm-projectile.el` with
`byte-compile-error-on-warn` true.
The new command is currently a dependency of `make test`. This should
ensure that contributors notice the warnings before submitting a pull
request. Alternatively we could have it as a separate make command and
run it separately on Travis if that's preferable, but this might result
in most people not seeing the warnings until the Travis build fails.
I didn't add automatic byte compilation of persp-projectile.el because it
requires a package which isn't included.
I had to use `--directory "."` so that emacs finds `projectile.el` while
compiling `helm-projectile.el`. I don't know why it doesn't
automatically have the path set correctly...
> Add check for byte-compiler warnings in make test

- CHANGELOG.md
- projectile.el
Haskell stack projects have both `*.cabal` files and a `stack.yaml` file.
Where as cabal projects only have `*.cabal` files.
If there is a `stack.yaml` file, users most certainly prefer to use stack
to build as it is the best way to get consistent builds for Haskell
projects.
Closes #884
> Prefer Haskell stack projects over cabal projects

- projectile.el
It can take a long time before
```elisp
(-mapcat #'projectile-dir-files
(projectile-get-project-directories))
```
completes. This makes it more evident what's happening.
Fixes #899
> Announce cache is empty before blocking.

- projectile.el
Projectile can't toggle between implementation and test correctly for python projects. This pull request update test prefix search predicates.
> Correct python project types used in the test prefix search.

- CHANGELOG.md
- README.md
- projectile.el
I've added check for string type for command read, cause in other case we should somehow detect if user's input is string compilation command or elisp function, so user input will only be requested if project's compilation command is a string.
> 907 Added elisp function call for run, test, compile commands.

- CHANGELOG.md
- projectile.el
This enables the user to customize the project name based on project-root. This is helpful in situations where the project base dir is not descriptive enough.
As an example, I use it like this:
```elisp
(defun fvaresi/projectile-custom-project-name (project-root)
(cond
((string-match "/Plugins/\\([^/]+\\)/\\(?:branches\\|tags\\)\\(?:.*\\)/\\([^/]+\\)" project-root)
(let* ((product-name (match-string 1 project-root))
(branch-name (match-string 2 project-root)))
(concat product-name "/" branch-name))) ;
((string-match "/Plugins/\\([^/]+\\)/trunk" project-root)
(let* ((product-name (match-string 1 project-root)))
(concat product-name "/trunk")))
;; do the default
(t
(projectile-default-project-name project-root))))
(setq projectile-project-name-function …
```
> Enable custom project names

- CHANGELOG.md
- projectile.el
This doesn't enable much more than switching between implementation and test files, but every little bit would seem to help.
> Add very basic emacs Cask project support.

- CHANGELOG.md
- projectile.el
Original advice was overriding the return from `compilation-find-file` with the result from other functions. This was causing other advices for `compilation-find-file` to be ignored.
I changed the advice to set the argument to the original function with the calculated value, thus having the desired effect, but now respecting the other advices.
> [Fix #871] Stop advice from overriding original function

- projectile.el
When adding `projectile-find-matching-test` support for emacs projects,
I found emacs projects have no standard regarding prefix or suffix---but
`projectile-test-affix` meant a prefix would always hide a suffix if you
listed both.
I believe the fact the result of `projectile-test-affix` was always
tested as both a prefix or a suffix speaks to its lack of value: better
to simply use the result of `projectile-test-prefix` as a prefix or the
result of `projectile-test-suffix` as a suffix directly.
`projectile-find-matching-test` and `projectile-find-matching-file` were
the only users of `projectile-test-affix`, so I simply eliminated it,
after modifying both of them to use the prefixes and suffixes properly.
> Check prefix *and* suffix when finding test files

- CHANGELOG.md
- README.md
- projectile.el
Add a command `projectile-edit-dir-locals' to quickly edit or create a
.dir-locals.el file for the project.
> Edit .dir-locals.el file of a project.

- CHANGELOG.md
- projectile.el
Workaround for https://github.com/bbatsov/projectile/issues/557 (Emacs 20703)
It now opens up the way for #947
> backport emacs 25 etags-tags-completion-table

- CHANGELOG.md
- README.md
- projectile.el
This is useful, for example, if you keep your OrgMode files in one git
repo but associate them with other projects in other directories.
This is a resubmission of #398 addressing Bozhidar's comments. Any feedback is appreciated, again!
> Allow setting projectile root as a file local variable.

- projectile.el
These two functions did not use the value of `projectile-test-prefix/suffix-function`. This changes `projectile-find-matching-test/file` to call the function stored in `projectile-test-prefix/suffix-function`, which default to `projectile-test-prefix/suffix`, respectively.
I'd like to add tests for this as well but don't have time right now, but I might be able to get around to it this week or next.
> Make `projectile-find-matching-{test/file}` respect `projectile-test-*-function`

- projectile.el
Hi,
projectile-find-other-file did not work with fossil. After investigating, I figured out that `fossil ls` gives a file list separated by `\n`, but projectile expects them separated by `\0`.
This changes the default projectile-fossil-command to give a zero-separated file list, just like the git and svn commands.
Unfortunately, `fossil ls` doesn't have a `-0` switch like `hg` and `bzr`.
> Make projectile work with fossil ls

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
As described in https://github.com/bbatsov/projectile/issues/955 I rand into difficulties when I was switching from the test file to the source file using `C-c p t`. 
When a matching count is calculated for files in the project root, the parameter `b` in the `projectile-dirname-matching-count` function will not have directory part, just the relative filename. The `file-name-directory` returns nil what the `split-string` cannot interpret, leading to the error "Wrong type argument: stringp, nil". Please see the added test case.
Solution: defaulting to empty string in this case solves the problem. I have added this safety check to the parameter `a` just in case although it seems always to be an absolute path at the moment.
>  Error while toggling between test and source file.

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Given the following tree structure:
```
./.git # git repo top-level
./front-end/
./front-end/.projectile
./front-end/src/...
./server/
./server/vendor
./server/vendor/a-git-submodule/
./server/vendor/a-git-submodule/.git
```
If the current top-level folder is `./front-end/`, and you invoke `projectile-find-file`, then `../server/vendor/a-git-submodule/` will leak into your choices. Presently, all submodules for the current repository are traversed, recursively so, regardless of whether or not those submodules reside within the current project root.
The attached patch resolves that issue.
Thank you for projectile!
> [Fix #952] Exclude out-of-project VCS submodules

- projectile.el
This handy function isn't mentioned anywhere, so add it to the docstring
to aid discoverability.
(Following on from #950)
> Mention projectile-remove-known-project.

- test/projectile-test.el
This test can fail if user-emacs-dir does not exist.  So make a
temporary known projects file, as is done in the test of
`projectile-merge-known-projects' in projectile-known-project-test.el.
I am currently packaging projectile for Debian, and the Debian package autobuild infrastructure sets $HOME to /nonexistent, causing this test to fail.
> fix test of `projectile-cleanup-known-projects'

- CHANGELOG.md
- projectile.el
Some C++ projects use the .hpp suffix for headers and .cc for source
files, and `projectile-find-other-file` function previously would not
work in this case. This commit updates the alist of associated file
extensions to link .cc and .hpp files in both directions.
> Associate .cc and .hpp files for C++

- projectile.el
- Look for rebar.config instead of rebar executable
- Add regex to toggle source/test files
This is only a partial fix for #965
> Improve rebar support

- CHANGELOG.md
- projectile.el
This pull request implements `projectile-replace-regexp` [as discussed and suggested by](https://github.com/bbatsov/projectile/issues/576#issuecomment-66892727) @shosti, and closes #576. The new `projectile-replace-regexp` replaces text by regexp within project files using `tags-query-replace`. `projectile-replace` has been refactored with a modified version of `tags-query-replace` to replace only literal matches (no regexp at all). This makes the behavior of these functions consistent with Emacs' `query-replace` and `query-replace-regexp`.
As it is very difficult to match the behavior of Emacs' regexps with grep tools, `projectile-files-with-string` is not used with `projectile-replace-regexp`, and has been adapted to support literal strings only.
I am definitely not the best Elisp …
> [Fix #576] Implement `projectile-replace-regexp'

- CHANGELOG.md
- projectile.el
When opening a file from the terminal, it is possible for the
file to be a project and have the `switch-to-buffer` hook run,
with a new buffer that has no associated file.
> Do not error inside of `projectile-cache-current-file` when opening a file inside a project.

- projectile.el
PR #946 copied the implementation from Emacs 25. However, Emacs 25
expects the function to return a list (see Emacs commit 0ac9d09b6dfe479),
whereas Emacs 24 expects an obarray:
Debugger entered--Lisp error: (wrong-type-argument vectorp ("BUILD_DIR" "CFLAGS" ...))
mapatoms((closure ((combined-table "Environment" "items" ...) (current-table "BUILD_DIR" "CFLAGS" ...) t) (sym) (intern (symbol-name sym) combined-table)) ("BUILD_DIR" "CFLAGS" ...))
(if combined-table (mapatoms (function (lambda (sym) (intern (symbol-name sym) combined-table))) current-table) (setq combined-table current-table))
(while (visit-tags-table-buffer (and combined-table t)) (setq current-table (funcall tags-completion-table-function)) (if combined-table (mapatoms (function (lambda (sym) (intern (symbol-name sym) …
> `etags-tags-completion-table` should return an obarray on Emacs 24.

- projectile.el
Thanks!
ivy-read allows you to specify a caller which is a more reliable version
of this-command. With ivy-completing-read you can't always tell which
command was called initially.
See https://github.com/abo-abo/swiper/pull/449#issuecomment-201832439
> projectile.el: ivy-completing-read -> ivy-read

- README.md
Explain that projectile-mode must be activated for Projectile to remember projects.  Fixes #992.
> Clarify initial usage instructions

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
This fixes an awkward bug when the current project is a symlink that
changes. Suppose we have the following filesystem layout:
/tmp/projectile_project -> /tmp/first_project
If we now delete /tmp/first_project and change the symlink:
/tmp/projectile_project -> /tmp/second_project
then `projectile-project-root-cache` will contain a key
`"projectile-root-bottom-up-/tmp/projectile-project"` with value
`"/tmp/first_project"`. This will stop `projectile-find-file` from working
as it can't cd to /tmp/first_project.
Instead, we enforce that the string from `projectile-project-root`
points to a directory that currently exists.
> Ignore cached project roots that point to nonexistent directories.

- CHANGELOG.md
- README.md
- projectile.el
- test/projectile-test.el
This adds a modifier (bang symbol !) for the `.projectile` file to override ignored files and ensure they are part of the project.
It works with paths and patterns:
```lisp
!/src/foo
!*.yml
```
Closes #892
> Let user override ignored files

- projectile.el
In order to use the `recompile' command, both `compilation-directory'
and `compile-command' variables need to be set.  This is taken care of
when using the `compile' function, but not `compilation-start'.
> Support use of recompile

- projectile.el
Commonly Scala tests are appended with "Spec".
This is a triage solution until #268 is implemented.
> Add "Spec" test suffix for SBT project type.

- projectile.el
When projectile root is different from the hg root (a subdirectory) projectile-dir-files-external returns incorrect results as they are relative to hg root not the projectile root dir. Fix this by forcing hg to return absolute paths.
> [hg] Fix hg locate

- CHANGELOG.md
- projectile.el
Use case-insensitive comparison on Windows to avoid false negatives from `projectile-project-buffer-p`. See #1013.
> [Fix #1013] Path comparison on Windows

- projectile.el
This is a small change, but I prefer getting feedback on when TAGS generation is done. At the moment, I end up pressing keys thinking 'is Emacs done yet?' as some of my projects take a few seconds to generate TAGS.
> Inform the user once TAGS has been regenerated

- CHANGELOG.md
- projectile.el
GNU global/ggtags-mode support was introduced in #267. This works well, but doesn't give the user the ability to control whether to use ggtags-mode or not. I imagine use cases where users would want to have the ability to control which backend to use for `projectile-regenerate-tags` and `projectile-find-tag` on a project-by-project basis.
> Commit allows turning gtags support off

- CHANGELOG.md
- doc/usage.md
- projectile.el
This is a helper function to go through the subdirectories of a
directory, check which ones are valid projects and add them to the cache
file. I didn't make it recursive although it could be. 
Thanks!
> Add projectile-discover-projects-in-directory

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
A minor annoyance for me while using projectile is that when I use `projectile-find-other-file`, it will often prompt me which file to use because it counts backup files as candidates. For example you have a project with 3 files, test.c, test.h and test.h~. If you are then editing test.c and use `projectile-find-other-file`, it will present both test.h and test.h~ as options, while the user probably wouldn't want to edit a backup file. So I think it would be better if this function ignored backup files.
The function didn't already ignore backup files, because it uses `file-name-extension`, which ignores backup suffixes. This pull request fixes this issue by filtering the candidates on not being backup files. I have also added a backup file to the files in the …
> Do not consider backup files for projectile-get-other-file.

- CHANGELOG.md
- projectile.el
Ensime creates a .ensime file, and .ensime_cache in the project directory.  The .ensime file is considered a project root, subordinate to the respective SBT, Gradle, or Maven files.  The .ensime_cache directory is ignored from indexing.
Thanks!
> Ignore ensime cache directory, and consider .ensime file as project root.

- Makefile
- doc/contributing.md
- projectile.el
- script/emacs.sh
- test/elpa.el
- test/make-compile.el
- test/make-update.el
- travis/provision.sh
Using e.g. the standard `cl-remove-if` in place of 4 aliases (`-remove`, `--remove`, `-reject`, `--reject`) improves code quality and eases new contributions and refactoring.
I've also rewritten `Makefile`, because any Cask-based `make test` stopped working on my system some time ago (and it fails intermittently on Travis CI as well).
I have more stuff on top of this PR in my develop branch, I'll open a new PR if this gets merged.
Thanks!
> Replace dash with cl-lib

- projectile.el
by the way, `make test` is broken on master
[16:28:08]matus@herakleitos:~
> cd .emacs.d/dev/projectile/
[22:41:57]matus@herakleitos:~/.emacs.d/dev/projectile
> make test
emacs -batch -l test/elpa.el -l test/run-tests
Cannot open load file: no such file or directory, noflet
make: *** [test] Error 255
Thanks!
> Change symbol to function.

- projectile.el
Modified function `projectile-switch-project-by-name`. Instead of calling `switch-project-action` from the current buffer, this is done in a temporary buffer after calling `hack-dir-local-variables-non-file-buffer`.
I think this fixes #413 and #1005 . It is the same solution I proposed there, but maybe easier to test for you with a PR.
Sorry I don't know how to add tests or `make test`. I don't think the changelog or readme should be updated since the function is not "visible".
Thanks
Thanks!
> load dir-locals before switching project

- .gitignore
- CHANGELOG.md
- Cask
- projectile.el
- test/projectile-test.el
This change makes it so that a direct `call-process` invocation is used
when it is possible to determine what binary should be used for the
command. This avoids the cost of shell startup time that is incurred
when `shell-command-to-string` is invoked instead.
Fixes #1044
> [Fix #1044] Prefer `call-process` to `shell-command-to-string`

- doc/contributing.md
When looking to contribute to the code part of the project, I noticed that the link to contribution guidelines on the doc site was broken. This fixes it!
> Fix URL of contribution guidelines in docs

- projectile.el
- test/projectile-test.el
Currently, `projectile-mode` adds 3 functions to `find-file-hook`. Moreover, it does so locally, while most people use `projectile-global-mode`. This means it's really hard to suppress the modifications to the hook, since it would have to be done for many buffers separately.
I propose to add only a single function to `find-file-hook` that calls all 3. Moreover, consider modifying `find-file-hook` globally, not locally.
One more thing: projectile's modification to `find-file-hook` makes it really slow to open a file on two unrelated remotes that I have: around 20 second delay difference. Should there be a variable to disable the hook functions on a remote file, or do you want to do it uniformly?
> Unify modifications to find-file-hook

- projectile.el
The `projectile-completing-read` interface now gets an optional `:action` arg that can be passed to the completion system (Ivy or Helm). For other completion systems, the behavior stays as before.
Now, functions like `projectile-find-file` or `projectile-switch-project` support advanced completion features such as:
- `ivy-next-line-and-call` or `helm-follow-action-forward`.
- `ivy-resume` or `helm-resume`.
- `ivy-occur` or the Helm equivalent.
> Extend the completion interface

- CHANGELOG.md
- README.md
- doc/index.md
- doc/usage.md
- projectile.el
Add two functions to check if Git projects are dirty
(uncommitted changes and/or unpushed commits).
Use [vc-check-status](https://github.com/thisirs/vc-check-status) package.
`projectile-check-project-dirty` check if the project associated with the given directory is dirty.
`projectile-see-dirty-projects` list all dirty projects (very useful before leaving Emacs after a day of hard work)
I used it for a while now and it work flawlessly for me.
If the community is interested, I can work on it a little more 
(add tests, maybe support for others vcs... ).
Thanks!
> Add check for dirty projects

- projectile.el
Using #'identity as action is necessary: otherwise `helm' returns nil.
Fixes https://github.com/bbatsov/persp-projectile/issues/5.
> projectile.el (projectile-completing-read): Fix up helm call

- doc/usage.md
This is a simple typo change in the docs that points to the proper example of binding projectile command map.
Thanks!
> fix incorrect hyperlink for command map binding

- CHANGELOG.md
- projectile.el
Without this, a GTAGS index in a parent directory takes precendence, which is generally undesirable.
> Add R DESCRIPTION file to `projectile-project-root-files`

- projectile.el
This PR fixes a problem I'm having on Emacs 25 in combination with Helm from a recent Melpa installation.
The way `helm` is called in `projectile-completing-read` is apparently problematic: the `:sources` argument gets passed a plain alist instead of a `helm-source` instance, thereby missing some slots which the constructor usually initializes. This leads to unusual matching behaviour, e.g. the input is not split on spaces properly, as Helm usually does.
The PR adds calling `helm-build-sync-source` instead. Moreover, it adds passing the `:prompt`, `:input` and `:buffer` arguments to `helm`.
---
Thanks!
> Use helm-build-sync-source

- projectile.el
After today's Melpa update containing  #1076, I noticed a mistake in the PR: `helm-build-sync-source` is a macro and might not be available at byte compile time. I fixed that by inlining the rather trivial expansion of the macro.
Sorry, should have noticed that before. It still generates a bytecode warning ("`helm-make-source` not known to be defined"); I'm not sure how to fix that properly.
Thanks!
> Helm build sync source

- CHANGELOG.md
- projectile.el
As of Emacs 25.1, `find-tag` is deprecated in favour of `xref-find-definitions`, so favour that command if it's defined.
Since `etags-select` has not been maintained since 2013, and xref offers all the same functionality (as far as I'm aware), I've set `'auto` to prefer xref over etags-seelct.
> Prefer xref to find-tag

- projectile.el
On the contrary, it's fixing a bytecode warning ;-)
> Silence byte-compiler

- projectile.el
`package.json` should not be a part of the root files list because;
* A lot of projects keep JS code in a subfolder. [example 1](https://github.com/olebedev/go-starter-kit) [example 2](https://github.com/olebedev/go-starter-kit)
* A lot of projects have multiple packages. See [learna](https://github.com/lerna/lerna)
I think `package.json` is not needed in the root file list. People could either initialize a version system or add a projectile file.
> Remove package.json from root file list

- CHANGELOG.md
- projectile.el
Only replace parts of the path that are located in the project's root.
> Create test files only within the project (#1072)

- .gitignore
Running `make` with Emacs 25.1.1 results in an _.elpa_ and _project_ directory that are not ignored.
> Ignore .elpa and project

- projectile.el
This improves performance slightly in many cases, and massively in a
few cases. The cache is invalidated whenever `buffer-file-name`
changes, so it should be pretty safe.
From #893:
> I've disabled the dynamic modeline for remote buffers as a temporary
workaround. I don't use tramp and I don't plan to fix this, so it's
up to someone else.
How does this solution look?
> Cache the name of the current Projectile project

- projectile.el
Very minor grammar fix in the documentation for the projectile-indexing-method
- [N/A] You've added tests (if possible) to cover your change(s)
- [N/A] You've updated the changelog (if adding/changing user-visible functionality)
- [N/A] You've updated the readme (if adding/changing user-visible functionality)
Thanks!
> Very minor grammatical fixes to projectile-indexing-method documentation

- projectile.el
Some times it's useful to rebuild tox environments. I think this command is great candidate for compile argument.
> Rebuild tox environments on project compile.

- projectile.el
Prevents Emacs from confirming setting of `projectile-project-type` value
in `.dir-locals.el`.
> Make projectile-project-type safe local variable

- CHANGELOG.md
- projectile.el
This should fix #523 and #835.
Don't merge this yet (it lacks changelogs, etc). Right now the idea is for people having the same problem to test if my fix actually fixes all scenarios.
The idea is pretty simple: only resolve project-root for local files, or when the remote files are _connected_.
So far this seems to resolve all the issues for me, but I only tested emacs `25.1`.
Things to test:
- `/scpx:user@host:somefile`
- `/sudo:root@localhost:somefile`
Note: by me, the issues only happened when `projectile-rails-global-mode` was turned on. Projectile alone worked pretty well. This is because `projectile-rails-mode` uses `projectile` to determine wether it'd turn on or not, and this was just too much for TRAMP.
> Fix TRAMP issues

- CHANGELOG.md
- doc/configuration.md
- projectile.el
- test/projectile-test.el
Added ability to add test files prefix and suffix during project type registration. Should improve toggling between implementation and test files functionality.
Thanks!
> Added ability to specify test suffix and test prefix during project registration

- doc/configuration.md
- doc/contributing.md
- doc/usage.md
* `doc/usage.md` (`projectile-edit-dir-locals`): Clarify which file is opened.
* `doc/configuration.md`:
- Fix code blocks (fix syntax errors, enable syntax highlighting, `#'`-quote functions).
- Reword section on directory-local variables.
> Touch-up documentation

- projectile.el
Similarly to package.json, these files may exist in subfolders if repositories have JavaScript packages that aren't at the top level (see #1092).
> Remove more JavaScript files from root file list

- projectile.el
- test/projectile-test.el
I have changed the way unignored directories are handled to make use of the optional directory argument provided by 'git ls-files'. This improves performance in the case where there are many files ignored by git in other directories (note that most of the gain is lost if a specific file is unignored since the entire list of ignored files must be retrieved in that case).
No user-visible functionality has been changed, and tests are passing after a tweak to support the new projectile-get-repo-ignored-directory function.
Feedback on this PR would be welcome, as this is my first attempt at contributing :-)
Thanks!
> Improve performance of unignore directive for directories.

- projectile.el
If a known projectile repository is unavailable or if projectile can't find the version control backend to use, `projectile-browse-dirty-projets` can run into an error.
This pull request fix this by doing some verifications (that the project folder is accessible and that a backend can be identified) before searching for modifications in projects.
> Don't check if unavailable projects are dirty

- CHANGELOG.md
- projectile.el
fixes #987
This is very hard to test (there are no existing `projectile-ag` tests).
> projectile-ag now respects ag-ignore-list

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Cache the result of (projectile-project-root) as a buffer local variable to
increase performance - this is implemented the same as was done
for (projectile-project-name) in PR 1906.
Should help resolve issue #1003
> Cache projectile-project-root for performance

- projectile.el
When switching projects need to ignore the cached value of the project root otherwise the old project is shown, not the new project.
I wonder if a similar approach could be taken for projectile-project-name here as well but I left it so as to keep the changeset as minimal as possible.
> Fix GH issue #1150

- CHANGELOG.md
- projectile.el
Replaces this pull (https://github.com/bbatsov/projectile/pull/1146) cuz my fork got all f-ed up.
[Fix #1119] [Fix #733] [Fix #680] 
Might fix [#1041]
Thanks!
> allow projectile-globally-ignored-dirs to operate on non-root dirs

- projectile.el
fix bug in `ag-ignore-list` usage (https://github.com/bbatsov/projectile/pull/1145#issuecomment-317276272)
Thanks!
> ag-ignore-list properly loaded with projectile-specific ignores

- CHANGELOG.md
- doc/configuration.md
- projectile.el
The build script for `npm` is currently `npm build`, which is invalid without arguments. Also, most npm users would expect the typical install hooks like `prepare` and `pre/postinstall` to be executed when building a project, and `install` also installs dependencies.
Thanks!
> Use npm install instead of build

- CHANGELOG.md
- doc/usage.md
- projectile.el
Some commands in projectile comes with an `-other-window` version with keybindings under the `4` prefix.
Sometimes I want to open a `dired` instance or a file in another frame and wonder why there is not `5`-prefix for frames. Well now there is, if this PR is merged. :)
- [ x ] The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
- [ - ] You've added tests (if possible) to cover your change(s)
- I don't believe it applies here. No new units to tests really.
- [ x ] All tests are passing (`make test`)
- [ x ] The new code is not generating bytecode or `M-x checkdoc` warnings
- No, but the old code sure is. ;)
- [ x ] You've updated the changelog (if adding/changing user-visible functionality)
- [ x ] You've updated the readme (if …
> Add -other-frame versions of commands that had -other-window versions

- CHANGELOG.md
- projectile.el
Add support for building and testing CMake- and Meson projects.
- [✓] The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
- With caveat that this PR adds support for two similar project types in one go. I can easily split this up if wanted.
- [✓] You've added tests (if possible) to cover your change(s)
- Does not apply I believe (?)
- [✓] All tests are passing (`make test`)
- [✓] The new code is not generating bytecode or `M-x checkdoc` warnings
- Not the new code no.
- [✓] You've updated the changelog (if adding/changing user-visible functionality)
- [✓] You've updated the readme (if adding/changing user-visible …
> Cmake and meson project support

- CHANGELOG.md
- projectile.el
I've been using this personally for a while but I think it makes sense to go in Projectile. This just registers "nix" projects as anything containing a "default.nix" file. "nix-build" actually both compiles and tests (if doCheck=true), should it be set for both?
Thanks!
> Add `nix' project type

- projectile.el
Thanks!
The project type is now displayed when a file a matching test or
implementation is not found, which is useful when the project type
has been mis-identified.
> Improve error message when file not found

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
`projectile-enable-caching` is important for performance for commands like `projectile-find-file`. However, the cache lives indefinitely (even across Emacs restarts) and can go stale if files are added/removed outside of Emacs.
Instead, allow the user to specify how long the cache may live by setting `projectile-files-cache-expire`, similar to `projectile-file-exists-local-cache-expire`.
> Allow the project files to list to expire after a time period

- projectile.el
Only use cached values if non nil (otherwise they match buffer's
buffer-file-name nil value in shell-mode).
Thanks!
> [Fix #1171 #1157] Don't use cached values when buffer-file-name is nil

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Treat members of `projectile-globally-ignored-file-suffixes` as file name suffixes. Previous treat as file extensions. By example, ignore ".min.js" in web project.
Thanks!
> Treat members of projectile-globally-ignored-file-suffixes as file name suffixes

- projectile.el
- test/projectile-test.el
This fixes `projectile-toggle-between-implementation-and-test` in recent rails apps.
Recent rails apps typically include `package.json` in the project root.
This messes up the projectile's project-type detection and sets it `npm` despite `rails-spec` or `rails-test`.
This also fixes: https://github.com/bbatsov/projectile/issues/1121#issuecomment-300851052
Original `projectile-detect-project-type` is looking into the `projectile-project-types` hash in **reverse** order of registration.
So if the registrations go in the order of this (and currently they do):
```
(projectile-register-project-type 'rails-rspec '("Gemfile" "app" "lib" "db" "config" "spec")
:compile "bundle exec rails server"
:test "bundle exec rspec")
(projectile-register-project-type 'npm '("package.json")
:compile "npm …
```
> Update `projectile-detect-project-type` for detecting order.

- CHANGELOG.md
- doc/usage.md
- projectile.el
- test/projectile-test.el
Make it possible to enforce out-of-tree compilation for build systems that can't build in-tree (eg. meson) while also making out-of-tree or in-tree compilation a preference for the user to set for build-systems that can do both (CMake, autotools etc).
These build systems usually needs to run a configure step before building so this PR adds a new command for that too.
As part of this I factored out the common body of `projectile-{compile,test,run}-project`, but these commands were behaving differently in subtle ways so this PR also makes them work the same. 
Specifically: 
- All these commands now run inside `(projectile-compilation-dir)`, not
just the compile command.
- All these commands cache the compilation command per directory
instead of per project (again not just the compile …
> Improved support for out-of-tree compilation

- projectile.el
With a long list of known projects, `projectile-browse-dirty-projects` (`C-c p V`) can take a while.
Dirty projects status is now cached and can be retrieved using prefix argument (`C-u C-c p V`).
Thanks!
> Allow to cache status of dirty projects

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Currently, the source directory and test directory are hardcoded
values ("src/" and "test/", cf. `projectile-create-test-file-for`)
This commit adds `:src-dir` and `:test-dir` as arguments to
`projectile-project-type` to make it easier to control where the tests
file are created.
Thanks!
> [Fix #1193] Add :src-dir and :test-dir to project-type

- doc/configuration.md
Following https://github.com/bbatsov/projectile/pull/1204, add documentation for `projectile-register-project-type` options.
Thanks!
> Document options to projectile-register-project-type

- README.md
- projectile.el
Read the Docs moved hosting to readthedocs.io instead of readthedocs.org. Fix
all links in the project.
For additional details, see:
https://blog.readthedocs.com/securing-subdomains/
> Starting today, Read the Docs will start hosting projects from subdomains on
> the domain readthedocs.io, instead of on readthedocs.org. This change
> addresses some security concerns around site cookies while hosting user
> generated data on the same domain as our dashboard.
Thanks!
> Prefer readthedocs.io instead of readthedocs.org for doc links

- CHANGELOG.md
- projectile.el
> Cache root in non-file-backed buffers

- CHANGELOG.md
- projectile.el
* projectile-ag doesn't seem to have any tests at the moment so I didn't add any.
* There is no functionality which needs adding to the readme.
> [Fix #1162] copy a read-only object instead of modifying it

- projectile.el
I found some setting for project could be declared by using `projectile-register-project-type`.
Thanks to #1204, #1207.
I beleive we are easy to understand that settings about a project type in the one place.
Note: I plan to add config (`src-dir` and `test-dir`) some project types if this PR is merged.
Thanks!
> Make project settings declarative

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
The return value of `projectile-default-configure-command` is checked
for nil, since `format` doesn't accept nil format strings.
> [Fix #1222] Don't pass nil format string to `format`

- projectile.el
This commit 
- fixes what I think is an error in the documentation of `projectile-git-submodule-command`: the default value doesn't list *files* in submodules, but submodule paths.
- explains how to deactivate listing submodule contents in `projectile-find-files`, solving #1174.  
Thanks!
> Improve documentation for projectile-git-submodule-command

- CHANGELOG.md
- projectile.el
This makes `C-u M-x projectile-vc` prompt you for a project directory to open.
It currently simply ignores a prefix argument that is interactively given.
> Add support for a prefix argument to projectile-vc

- projectile.el
> Fix projectile-vc calling projectile-completing-read regardless of the prefix argument

- projectile.el
This adds support for clojure deps.edn - based projects which also fixes switching between test/implementation files with `projectile-toggle-between-implementation-and-test` function.
> [Fix #1235] support for clojure deps.edn projects

- projectile.el
Mostly taken from @nlamirault's [`projectile-ripgrep`](https://github.com/nlamirault/ripgrep.el/blob/a1f8f030bf5daea92dd13b953720a6c13dd3557c/projectile-ripgrep.el).
@bbatsov If you'll make me a collaborator on this project, I can merge this and perhaps other PRs as well, as I am doing for `helm-projectile`.
> Add `projectile-ripgrep`

- CHANGELOG.md
- projectile.el
- test/projectile-known-project-test.el
Projectile adds projects as directory names, as in `~/project/`.
Manually adding a project root that is not a directory name, as
in `(projectile-add-known-project "~/project")`, works fine, but
Projectile will then add the project root as a directory name, so that
both `~/project` and `~/project/` will be in the list of known
projects.
This change converts `~/project` to `~/project/` before adding it to
the list, thereby avoiding annoying near-duplicates.
Thanks!
> Ensure project-roots are directories

- CHANGELOG.md
- test/.gitignore
- test/projectile-known-project-test.el
- test/projectile-test.el
This test was blowing away the actual project file, rather than a test
file. To fix this, move the test to the known-project-test file and
give it test-tmp-file-path.
> [Fix #1246] Give clear-known-projects test temp project file

- CHANGELOG.md
- projectile.el
Remove declaration of `projectile-mode-line` as an autoload.
Fixes bbatsov/projectile#1080
> Don't autoload defcustom

- projectile.el
Fixes #1165 
Mac users, inc. myself, seemed unable to discover new projects. Root
cause seemed to be a 'sticky' projectile-cached-project-root
dynamically-scoped variable.
Setting this to the dir variable, along with default-directory, fixes
the issue.
Can't seem to test - I get an error:
`Cannot open load file: No such file or directory, noflet`
Thanks!
> Fixed projectile-discover-projects-in-directory command

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
When enabling projectile-global-mode every time a new file buffer is
opened, a "No projects needed to be removed." message is triggered.
These messages are not helpful to the user, clutter the messages buffer,
may obscure other more informative messages in the mini buffer, and are
rather annoying.
> Avoid "No projects needed to be removed." messages in global mode

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Buffers are created by other packages that appear on projectile's buffer lists, but they always have
some variation that makes impossible including all possible name cases, thus regular expressions
come handy for this sort of cases. This commit allows `*-ignored-*-p` functions to work with regular
expressions.
Thanks!
> ignored-*-p: Match against regular expressions

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
to handle files with characters like "+" in them correctly.  Such characters should be matched
literally instead of ending up as part of a regexp.  This happens for example with Objective-C,
where it's common to have two files of the form Class+Protocol.{m,h}.
> Use regexp-quote in projectile-get-other-files

- projectile.el
Fixes "You're not in a project" error when remote is not connected yet.
Thanks!
> [Fix #1252] Switch to unconnected remote projects

- projectile.el
When `projectile-track-known-projects-automatically` is nil, we have to add new projects explicitly with `projectile-add-known-project`. But if I do this and then restart emacs, the newly added project is not remembered. To fix this, an optional argument `MERGE` is added to `projectile-add-known-project`. When it is non-nil (which is the case in interactive calls), `projectile-merge-known-projects` is called at the end of the function.
I didn't add the `projectile-merge-known-projects` call unconditionally because I see that `projectile-add-known-project` is called by `projectile-discover-projects-in-search-path` and it seems to me that we don't want to store these projects persistently. But if that's not the case, then it would perhaps be simpler to remove the optional argument and add …
> Remember explicitly added projects

- CHANGELOG.md
- doc/configuration.md
- projectile.el
- test/projectile-test.el
This allows for the implementation of IDE-like features where projectile could context-sensitively change the value of the command to execute for a given command type.
An example usage of this feature would go as follows:
```elisp
(defun my/compile-command ()
"Returns a String representing the compile command to run for the given context"
(cond
((and (eq major-mode 'java-mode)
(not (string-match-p (regexp-quote "\\.*/test/\\.*") (buffer-file-name (current-buffer)))))
"./gradlew build")
((eq major-mode 'web-mode)
"./gradlew compile-templates")
))
(defun my/test-command ()
"Returns a String representing the test command to run for the given context"
(cond
((eq major-mode 'js-mode) "grunt test") ;; Test the JS of the project
((eq major-mode 'java-mode) "./gradlew test") ;; Test the Java code …
```
> Add support for function symbols as project default commands

- projectile.el
I could not get the tests running: ``No rule to make target ".../projectile/.cask/26.1/elpa"``. But the tests in CI did aparently pass, so at least I did not break anything.
> fixes #1274

- CHANGELOG.md
- projectile.el
Otherwise it would generate empty TAGS files on some systems
> [Fix #658] Specify project path for projectile-tags-command

- CHANGELOG.md
- projectile.el
- Adds a  "_test" `:test-suffix` for Python projects.
- Adds support for [Pipenv](https://pipenv.readthedocs.io/en/latest/) projects
Resolves #1237 
Thanks!
> Add support for Pipenv projects, python test suffixes

- CHANGELOG.md
- README.md
- projectile.el
- it generates a `.dir-locals.el' file which controls the read-only behavior.
- logic is copied from ggtags.
> Implementing #972: Add toggle for project read only mode.

- test/projectile-test.el
Migrates a few tests to the new-style as per https://github.com/bbatsov/projectile/issues/1303
These are tests I found at the bottom of `projectile-legacy-test.el`, so hopefully it doesn't conflict with anybody else's work on this issue.
Thanks!
> migrate some serialization tests to buttercup

- projectile.el
The call to `projectile-files-ext-command` returns filenames relative
to the project root, not to the current directory.
> Fix get-immediate-sub-projects

- test/projectile-legacy-test.el
- test/projectile-test.el
The test case `~/project and ~/project/ should not be added separately to the known projects list` (L140) is kinda brittle, I had to change the test folder name from `~/a/` to `~/project/` otherwise the test would fail whenever the prior test on L136 was run as well. Let me know if this sounds like a problem 😃 
- [x The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
Thanks!
> tests for add-known-project, configure-command, get-all-sub-projects

- projectile.el
Fixes a little quirk in the mode line when (gasp!) not working in a recognised project.
> Avoid ":nil" project type string in mode line when not in a project

- projectile.el
Added a function projectile--move-current-project-to-end which will move current project to the end of the list while switching projects. Earlier it was being removed
> [Fix #1016] Switching projects does not include the current project

- .dir-locals.el
Disable `indent-tabs-mode` correctly.
The previous settings will turn on `indent-tabs-mode`.
Thanks!
> Correctly set the dir-local variable indent-tabs-mode to nil

- CHANGELOG.md
- projectile.el
~~3~~ 2 options are implemented:
- all-buffers (corresponds to the existing behavior)
~~keep-processes~~
- kill-only-files: kill only the buffer that have a buffer-file-name.
changelog:
* projectile-kill-buffers-filter: new defcustom.
------------- 
Note:
- option 2 corresponds to the use-case described in #1233  
- maybe option kill-only-files is not useful; and maybe other choices are. Suggestions are welcome!
edit: eventually kept only `kill-only-files`, while allowing any predicate to be used.
cc @mfiano 
fix #1233
> Add a new defcustom to configure projectile-kill-buffers.

- CHANGELOG.md
- projectile.el
Here external command = caller of `projectile--run-project-cmd`.
Implemented is a non-prompting version that repeats the last command run, merging test, compile, configure etc commands.
Fix #1279
cc @phillord 
To be discussed: can anything interesting be done with the command history? maybe a prompting version could be interesting.
before merging:
> Add a command to re-execute the last external command in a project.

- doc/configuration.md
I tried setting the function to something along the lines of the old syntax of customizing projectile-mode-line to "'(:eval (format " Proj[%s]" (projectile-project-name)))" as mentioned in the _stable_ documentation.
This confusion cost me about an hour, so I thought giving an example might help somebody else.
Thanks!
> Updated docs: gave an example for projectile-mode-line-function

- projectile.el
- test/projectile-test.el
projectile-completing-read and projectile-dir-files: check that argument is a directory, otherwise early exit. 
projectile--directory-p: new function (a robust version of file-directory-p).
> Check directory arguments passed interactively.

- projectile.el
This was removed in 90997d6, but I find it handy as a warning that I
might be killing the wrong project. If I mean to kill one with only a
few buffers and I see the message "kill 20 buffers", I'll be saved
from making a very annoying mistake.
Plural/singular handling probably doesn't matter much. Personally, I
would never use this command for a project with a single buffer -- I
would just use `kill-this-buffer`.
Thanks!
> Bring back buffer kill count message

- projectile.el
- test/projectile-test.el
- When using alien indexing method projectile currently returns the
full paths to files in submodules, this makes filtering in hybrid
mode to break because the ignore patterns would be matched against
the absolute path to submodules files, instead of relative to
project root
In the projectile 1.0.0 release, files are searched and then processed to make them relative to project root:
https://github.com/bbatsov/projectile/blob/09d1ef17a20c42dc6a2b1622df8faa8fb1c6ad9f/projectile.el#L990
But this has since been refactored and was broken.
This PR fixes #1353
Thanks!
> Alien indexing submodules should return relative paths

- projectile.el
`recentf-list` contains paths relative to `~` (e.g. `~/projects/project/x/y/z`), `projectile-project-root` returns an absolute path (e.g. `/home/user/project/project`), so `projectile-recentf-files` always returns an empty list as `/home/user/project/project` is not a prefix of `~/projects/project/x/y/z`.
Thanks!
> fix empty projectile-recentf

- projectile.el
**don't merge yet**
-----
Projectile uses this defadvice for `delete-file`:
``` elisp
(defadvice delete-file (before purge-from-projectile-cache (filename &optional trash))
(if (and projectile-enable-caching (projectile-project-p))
(let* ((project-root (projectile-project-root))
(true-filename (file-truename filename))
(relative-filename (file-relative-name true-filename project-root)))
(if (projectile-file-cached-p relative-filename project-root)
(projectile-purge-file-from-cache relative-filename)))))
```
It does the right thing, except it's very annoying when you delete a huge directory through `dired` for example, because it slows down the deletion by an order of magnitude.
There are several options around this problem:
- Add ability to disable the above advice, and let the user deal …
> Port advices to new mechanism

- .gitignore
- CHANGELOG.md
- Makefile
The functionality has been basically copied from cider and now we can call make
in order to produce projectile.elc.
> Fix the Makefile so that we can compile projectile

- doc/configuration.md
- projectile.el
Adds documentation on the different sorting methods and how they interact with the alien indexing method. I found the different methods a little bit confusing, and especially that they didn't work when alien indexing was turned on.
> Add documentation for projectile-sort-order

- CHANGELOG.md
- projectile.el
Adjust the wildcard used to detect cabal projects to exclude a
`.cabal` dotfile (or dot-directory).
When using cabal, a `.cabal` directory will exist inside the user's
home directory. Without this change, projectile will interpret that as
a Cabal project existing directly in the home directory, and thus
every file opened that does not belong to a more specific project will
be categorized as a Haskell Cabal project.
Fixes #1391.
> Fix cabal project detection

- CHANGELOG.md
- doc/projects.md
- projectile.el
- test/projectile-test.el
This PR enables users to pass a list of custom functions to `:related-files-fn option` so that multiple custom functions can be merged effectively.
This PR also adds several helper functions to generate common custom functions easily. These helper functions can be used with other user-defined custom functions.
Example of helper usages:
```el
(setq my/related-files
(list
(projectile-related-files-fn-extensions :other '("cpp" "h" "hpp"))
(projectile-related-files-fn-test-with-prefix "cpp" "Test")
(projectile-related-files-fn-test-with-suffix "el" "_test")
(projectile-related-files-fn-groups
:doc
'(("doc/common.txt"
"src/foo.h"
"src/bar.h")))))
(projectile-register-project-type
;; ...
:related-files-fn #'my/related-files)
```
- [n/a] You've updated the readme (if adding/changing user-visible …
> Add :related-files-fn custom function helpers

- projectile.el
Make `projectile-ripgrep` work like `projectile-ag`.
Specifically
- Expose the prefix arg as an actual argument
- Show that we're doing a regexp search
- Update docstring
> Make projectile-ripgrep work like projectile-ag.

- CHANGELOG.md
- projectile.el
Bloop is a Scala Build Server. Projects using bloop will likely have another build system referenced locally, e.g. a `build.sbt` file, but the ideal method to compile/test will be through the `bloop` command to the `bloop` daemon.
Thanks!
> Add Bloop Configuration

- doc/contributing.md
There was an extra "the" in the Contributing section of the docs. This deletes it.
Thanks!
> Remove extra "the" from Contributing docs

- CHANGELOG.md
- doc/configuration.md
- projectile.el
The patch make fd the default for searching for files in non-DVCS
projects.
> Use fd when available instead of find

- projectile.el
Prevent projectile-find-file to be littered with escape codes when the
environment variable `LS_COLORS` is set.
Similar PR as for downstream: https://github.com/hlissner/doom-emacs/pull/1449
Thanks!
> fd never use colors

- CHANGELOG.md
- projectile.el
This PR fixes an issue encountered when working in a go project that doesn't have any `.go` files at the root. The fix is to check for a `go.mod` file at the root of the project, avoiding a recursive descent of the project. The `go.mod` file is new-ish and will be present in projects that are using Go modules. The file will be present in all (or almost all) Go projects when Go 1.13 is released later this year.
I didn't add any tests, but this is the fix I applied to my local install of projectile and it worked great.
Feel free to remove or tweak my Changelog entry, this change may not be big enough to warrant documentation.
> Enhance go project detection by referring to go.mod file

- projectile.el
Fix a typo when calling projectile-compile-project in python projects: The setup file should by setup.py, not setup.by (note 'p' vs 'b').
> Fix typo in setup.by ('p' vs. 'b').

- projectile.el
Fix projectile-compile-project in go projects: Calling `go build ./...` doesn't build a binary.
> Fix go build: go build ./... doesn't create a binay.

- doc/configuration.md
I would have liked to see this when checking the docs - I had to look for this longer than I'd wanted. Veteran Emacs users probably check the list of configurable variables first, but those using Emacs as a secondary tool  (like me) usually check the docs first.
Relates to #1016 
Thanks!
> Add projectile-current-on-switch information

- CHANGELOG.md
- projectile.el
Fixes: https://github.com/bbatsov/projectile/issues/1270
Equivalent to: https://github.com/bbatsov/projectile/pull/1268 (but error is still signalled if command is invalid)
Generalizes: https://github.com/bbatsov/projectile/pull/1269
This fixes the regression introduced in https://github.com/bbatsov/projectile/pull/1255 that prevents a user from running a command when it doesn't have a default value.
@bbatsov originally proposed in https://github.com/bbatsov/projectile/pull/1269 that the solution could be generalized by prompting the user; but if we did this, we would prompt the user twice when using projectile-*-project commands. By returning nil, we leave it up to the caller to handle errors. This is equivalent to the behaviour before https://github.com/bbatsov/projectile/pull/1255.
--- …
> Return nil when a command doesn't have a default value

- projectile.el
As a follow up to #1454, this only autoloads `projectile-add-known-project`, as it is an interactive command.
> Autoload projectile-add-known-project

- Makefile
Hi!
I found your Makefile has typo; `PGKDIR`.
I try to fix it but your build depends `PGKDIR` (nil). so I use `elpa` instead of it.
All make job works well in my environment, but please try it.
----
Thanks!
> Makefile: use elpa instead of PKGDIR

- projectile.el
Bloop project type should have the same test-prefix as sbt project type ("Spec").
Thanks!
> Add test-suffix, test-dir and src-dir to bloop project type

- projectile.el
----
vterm: Add declare-function invocations.
vterm, ggtags, pkg-info, ripgrep: Add "ext:" to denote external
packages. Separate from core Emacs features.
Thanks!
> Placate byte-compiler.

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
When a project is configured via `.projectile` to include multiple directories
explicitly this results in `projectile-grep` to run over multiple roots.
```
+/foo/bar
+/baz/
```
With a single global *grep* buffer this results in either
a) losing all but the search result of the last root
b) Stalling as the user is asked per root to kill the grep buffer
To avoid this the name of the `*grep*` buffer should to include the current
`root` being search associated with the buffer like `*grep <~/source/foo/bar>*`.
Fixes #1482
> Allow multiple root-dirs to be search by projectile-grep

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
When using hybrid mode and unignoring files that are ignored by git, the
settings in .projectile would not work. The arguments to internal
function projectile-get-repo-ignored-directory were in the wrong
order. So it would return nil instead of the desired list of git ignored
files.
~~The issue is caught by the projectile-add-unignored test.~~
Looks like I was mistaken and this needs a test.
> [Fix #1475] Fix unignoring directories in hybrid mode

- CHANGELOG.md
- projectile.el
Hey! Thanks for projectile. As a disclaimer I don't write very much Lisp (yet).
I need to fire multiple terminals in the projects I work on. One to run the server and follow the logs, maybe an interactive console and some other bits & bobs sometimes so add a mechanism to override the default behaviour and spawn new vterm buffers as needed.
Going to copy and paste my commit if that's OK:
>If `projectile-run-vterm` is called with a prefix ARG it will generate
> a new buffer in the style of `generate-new-buffer-name` (e.g '*vterm
> my-proj<2>*') and switch to it.
Thanks!
> Allow Projectile to spawn extra process buffers (shell/eshell/term/vterm/ielm) with the prefix ARG

- CHANGELOG.md
- projectile.el
When I am working on a big project and I have opened a file, deep into the directory structure, it's annoying to navigate the GDB execution to the build folder. (Lots of `../../`). With the new function in this, GDB can be executed at the root of the project which allows an intuitive path for the build folder to be given.
> Adding project command for GDB.

- CHANGELOG.md
- projectile.el
When TRAMP archives are enabled, back out of the archive before trying to find
the project root. Starting inside the archive makes opening archives quite slow.
- Would require gvfs, as far as I know.
- Don't pass locally, with or without this change.
> Leave archive before searching for project root

- projectile.el
This avoids "cd \<project root\>" as first line of the newly created terminal and is consistent with other functions, e.g. `projectile-run-term`.
I did not update `CHANGELOG.md` because this is a really small enhancement, even if it is user-visible.
Thanks!
> Use projectile-with-default-dir in projectile-run-vterm

- projectile.el
Added a compilation directory for cmake projects.
Now it builds the project under 'build' instead of in source.
> Add a compilation-dir for cmake projects.

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Originally reported under bug #675, native indexing for non-trivial
projects is extremely slow due to repeated invocations of
(projectile-ignored-[files|directories]) during recursion.
@shitikanth proposed a solution under #1495 in Feb 2020.
This PR incorporates @bbatsov's feedback on #1495 and may
resolve #1495 and close #675.
Thanks to @shitikanth for initial research and solution idea.
Benchmarking suggests at least a 10x improvement.
e.g.: indexing the projectile source project itself under linux:
(benchmark-run 3 (projectile-dir-files-native default-directory))
OLD: (2.109717349 25 0.5421294649999999)
NEW: (0.098484531 1 0.022120505000000013)
The effect was even more pronounced for me on Windows.
Before submitting a PR make sure the following things have been done …
> Improve performance of native indexing.

- test/projectile-test.el
Fix a small whitespace error, which causes `codespell` to suggest that `files'` should be replaced `file's`.
> Fix whitespace

- CHANGELOG.md
- doc/projects.md
- projectile.el
- test/projectile-test.el
Resolves bbatsov/projectile#1522
Setting the customizable `projectile-dirconfig-comment-prefix` variable to a character, e.g. `?#`, will cause lines in the .projectile which start with that character to be skipped over instead interpreting them as paths.
Thanks!
> Support for optional comments in .projectile files by customizing projectile-dirconfig-comment-prefix.

- projectile.el
The change in 65ba429, while good, don't necessarily allow projectile to recognize go modules (usually living in ~/go/pkg/mod) as bonafide projects.
> accommodate golang modules

- CHANGELOG.md
- projectile.el
I've added two new customs that can be used to control the feature suggested in #1523. The check if the current buffer count is cover the cap is performed every time the `find-file` hook is executed *and* projectile mode is active. 
> Adding support for limiting project buffer count

- CHANGELOG.md
- doc/projects.md
- projectile.el
This PR adds a new projectile project type for the Bazel build system. It's multi-language, multi-platform, so I've placed it under the "Universal" category. Its marker file is `WORKSPACE`, and commands for building, testing and running are `bazel build`, `bazel test` and `bazel run` respectively.
I've tried to run `make test`, and there's one test that's failing on both master and my branch. I'm not sure if it's related to my change.
Fixes https://github.com/bbatsov/projectile/issues/1465
```
projectile-project-root ensures that we update the cache if it's expired
Traceback (most recent call last):
(let ((default-directory sandbox)) (progn (make-directory "project/" t) (l...
(progn (make-directory "project/" t) (let ((temp-file "project/.projectile...
(let ((projectile-projects-cache …
```
> [Fix #1465] Add Bazel WORKSPACE detection to Projectile

- CHANGELOG.md
- projectile.el
> Add :test-suffix to Angular projects

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
This PR adds a custom setting `projectile-auto-discover` that controls whether to automatically run `projectile-discover-projects-in-search-path` when Projectile mode is activated.
The main purpose is to enable faster Emacs startup when starting `projectile-mode` automatically from the init file. On my system (~2015 i5, Emacs 27, Linux, with 140 project directories) turning off auto-discovery improves startup time by around 1.7 seconds.
The default setting for `projectile-auto-discover` leaves current behavior unchanged. 
One already has to manually run one of the `projectile-discover-*` commands to update project bookmarks during an Emacs session, so it seems reasonable to allow the user to choose to always use manual updating rather than forcing an update every time they start Emacs or …
> Add a custom setting to control automatic project discovery

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
[Eldev](https://github.com/doublep/eldev) is a build tool for Elisp projects, comparable to Cask. Normally I would create a separate package (like I did for [Flycheck](https://github.com/flycheck/flycheck-eldev)) for integrating it, but since this is only a few lines, I feel it would be an overkill.
Eldev is virtually unused currently, but this is chicken-and-egg problem: if I integrate it in more places, *maybe* it will get more users as a side-effect.
Thanks!
> Add emacs-eldev project type

- CHANGELOG.md
- projectile.el
Added as first option, like in [spacemacs](https://develop.spacemacs.org/doc/DOCUMENTATION.html#searching) and [visual studio code](https://code.visualstudio.com/updates/v1_11#_text-search-improvements).
Add ripgrep search option to the `projectile-files-with-string` function
I will check all boxes below (although I did not really check all these things as I consider it not very relevant here), as this is a minor addition that is succesfully tested on Fedora 32.
Also it is probably useful to mention here that I actually implemented this option as a fix to issue  #1554 (which describes that the grep and ack search options return errors here) 
- [ x] The commits are …
> Add ripgrep search option

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
This adds install and package commands useful for cmake workflow. Package and install defaults are added for cmake projects, and install defaults for make project. The new commands are mentioned in the docs.
Both command additions are based on the existing test command.
Thanks!
> [Fix #1560] Add install and package project commands

- CHANGELOG.md
- projectile.el
Adds a python-poetry project type for [poetry](https://python-poetry.org/) based python projects. Poetry has become increasingly popular, and currently isn't getting recognized as a project type as poetry removes the need for a `setup.py` file.
Thanks!
Edit: Had to fix one of the commands.. everything should be good to go now 👍
> Adds python-poetry project type

- projectile.el
Update eldev-emacs project type for:
7ed2ce3 * [Fix #1560] Add install and package project commands
95bcc7d * Add a `:project-file` param to `projectile-register-project-type`
> Update eldev-emacs project type with recently added features

- projectile.el
ccls (https://github.com/MaskRay/ccls) saves some files into `.ccls-cache` in
the project directory. These are generally uninteresting to the user.
----------------
Thanks!
> Add .ccls-cache to projectile-globally-ignored-directories

- projectile.el
[This commit](https://github.com/bbatsov/projectile/commit/41461d9d3a41953d55dc03262cfe6eb0e71ea645) has unbalances quotes and breaks projectile.
> Fix missing quote

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
Although relatively new, [Dune](https://github.com/ocaml/dune) has become the de-facto standard build tool for OCaml. The vast majority of packages on [Opam](https://opam.ocaml.org/packages/index-popularity.html) uses Dune now.
Reference for project root file: https://dune.readthedocs.io/en/stable/overview.html?highlight=dune-project#project-layout
Thanks!
> Add support for OCaml dune projects

- CHANGELOG.md
- projectile.el
[#1377](https://github.com/bbatsov/projectile/issues/1377): Fix `projectile-regenerate-tags` directory.
> [Fix #1377] Modify tags generation to use directory file name

- CHANGELOG.md
- projectile.el
Previously, `projectile-ibuffer` was very slow for me - this is due to calling `projectile-project-root` (which is rather slow) on all buffers. However, there exists already a function `projectile-project-buffer-p` which is much faster - which can be used to isolate buffers which have no chance of being in the directory. 
The only question is whether this is correct - as far as I know if a buffer's default directory is not under a project root, it cannot be within a project. I'm also assuming this function works correctly over tramp (as I haven't tested it on tramp), although it seems to test that properly (?). 
I did find one discrepancy, currently `projectile-ibuffer` seems to include modes that are ignored by other projectile functions (at least `projectile-globally-ignored-modes` - …
> Optimize ibuffer support to avoid calling projectile-project-root

- projectile.el
In recent version of clangd, the clangd cache directory moved to `$PROJECT/.cache/clangd`. See https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/index/Background.h#L61
> Ignore clangd cache directory

- projectile.el
@bbatsov See #1603. I started fixing a few things here and there but I am not sure if this is the right thing to fix the root cause once and for all. Is there a reason not to use `projectile-acquire-root` everywhere? Simply never use `projectile-project-root` and `projectile-ensure-root`. This would at least eliminate this problem completely. I am not sure if this would break some things since you might want to use the functions in hooks and there one might want to prefer an error?
An even cleaner design would probably be to never ask the user and add a project argument to every interactive function, where the interactive argument is supplied by asking. If a function is not used interactively then the argument must be supplied. But I am not sure if such a change is still possible with the …
> Use projectile-acquire-root and fix some nil errors

- projectile.el
Hi @bbatsov, The first thank you for the great package.
I would like to send a PR, that is useful for me.
`projectile-compile` will have separated compile-history by using `projectile--get-command-history`. If something needs to be improved please tell me, I will try to resolve it.
Hope it is useful!
Thanks!
> Separate compile-history

- projectile.el
I've made `projectile-run-{shell,eshell,ielm,term}` accept an optional prefix argument, to make them consistent with `projectile-run-vterm`. Please let me know if there was a reason for making these function behave in a different way.
Since eldev seems to not be packaged in guix yet, I was not able to run the tests. My apologies!
> Make prefix argument optional for all shells.

- CHANGELOG.md
- README.md
- projectile.el
This PR replaces legacy Erlang build tool `rebar`, that largely fell out of use, with the contemporary version called `rebar3`.
`rebar` script is no longer in active use in the Erlang world, so it makes sense to update the defaults.
Thanks!
> Switch to rebar3

- projectile.el
- test/projectile-test.el
If a command fails, it may return an error message like:
`fatal: No url found for submodule path 'XXX' in .gitmodules`.
It just filters out error messages to avoid the calling code to try to
use it as a file name.
Thanks!
> Make sure projectile-files-via-ext-command returns files not errors

- projectile.el
- test/projectile-test.el
This makes sure that any buffer local variables that were loaded by
`hack-dir-local-variables-non-file-buffer` are loaded with the
appropriate variables when the action is called.
Also removes the code to set project name to the new project as it should be properly set given we're now running from the new project's buffer.
- ~I'm not sure of how/if this should be tested, open to suggestions~
Thanks!
> Call `switch-project-action` within project's temp buffer

- projectile.el
- test/projectile-test.el
Closes #1603
This pull request implements the changes described in #1603. As of now, some functions will no longer throw a `stringp type error`, so they will either:
- Prompt the user to select a project when `projectile-require-project-root` is `'prompt`
- Throw a friendly error when `projectile-require-project-root` is `t`
- Use `current-directory` when `projectile-require-project-root` is `nil` (same behavior as before).
I couldn't verify any `string type error` in the following functions:
- `projectile-next-project-buffer`
- `projectile-previous-project-buffer`
Thanks!
> Make projectile-require-project-root setting work on project-less files

- projectile.el
When calling projectile-vc outside of a project directory, it crashes with
abbreviate-file-name: Wrong type argument: stringp, nil
This change makes it use projectile-acquire-root, which may prompt the
user or display a nicer error message in this case.
> Use projectile-acquire-root in projectile-vc

- projectile.el
- test/projectile-test.el
As discussed in #1617, manually switch to the correct buffer after exiting from `with-temp-buffer`.
Adds tests for both cases mentioned in #1617, and they fail without the change so in that sense it should be solid.
I didn't update the changelog or readme as I'm not sure how you want to indicate this especially since it's fixing a regression from another already-logged change (#1450).
> [#1617] Switch to right buffer in projectile-switch-project-by-name

- projectile.el
- test/projectile-test.el
In 351e0c3b430392c73372f4129b1174c088a934b2 I switched from
`shell-command-to-string` to `call-process-shell-command` so that we
could capture only the stdout, not the stderr.
However, `call-process-shell-command` does not support magic
filenames, which breaks the use of `projectile-files-via-ext-command`
in TRAMP for example.
In this commit we swich to `shell-command`, which supports both
separating stdout and stderr and magic handlers.
Thanks!
Fixes #1616
> projectile-files-via-ext-command: support magic filenames

- doc/modules/ROOT/pages/usage.adoc
A missing keyboard shortcut in the docs.
Thanks!
> [Docs] Add missing keyboard shortcut for "Toggle between related files"

- projectile.el
Though the documentation of `projectile-indexing-method` does mention
that sorting and filtering isn't applied when the `alien` method is
used.  Many people misses it, so add a mention for each custom
variables that can be affected.
Address issue #1508.
Thanks!
> custom doc: Mention when the variable isn't effective with alien

- projectile.el
It's useful to see any error messages that these commands return.
This also fixes another issue: previously if pop-up-frames was non-nil and an
error occurred then a new frame would be opened to display the error buffer. But
the error buffer would be immediately deleted by `with-temp-buffer`, leaving an
additional frame displaying the users current buffer.
The use of `save-window-excursion` worked around this issue when only Emacs
windows were in use, which is perhaps why no-one noticed.
Fixes #1631
I don't think this change is unit-testable, so no tests. I'll update the changelog if you want to merge this.
Before submitting a PR make sure the following …
> Display any errors from projectile files external command

- doc/modules/ROOT/pages/extensions.adoc
Thanks for one of the best emacs extensions around! Just fixing a broken link in the extensions page in the documentation for https://github.com/emacs-lsp/lsp-mode[lsp-mode]
- [] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [] You've updated the readme (if adding/changing user-visible functionality)
Thanks!
> Just fixing a broken link in the extensions page for https://github.com/emacs-lsp/lsp-mode[lsp-mode]

- projectile.el
Updates git-submodules-command to use $displaypath rather than $path.
$displaypath returns the path to a module relative to the current working directory whereas $path (used previously) only returns the path relative to the git root. 
This causes issues with function `projectile-get-sub-projects-command` when the git root is not the same as the project root.
Thanks!
> updates git-submodules-command to fix relative paths

- projectile.el
More explanation was added as to how the asterisk prefix works, based on
the fabulous documentation by ntc2, here:
https://github.com/bbatsov/projectile/pull/1153#issuecomment-401146353
> Added better documentation on asterisk prefix

- CHANGELOG.md
- projectile.el
Do not ask twice for the project root when calling
`projectile-run-ielm`, `projectile-run-term` or `projectile-run-vterm`
from outside a projectile folder.
Use `projectile-with-default-dir` at the beginning of those functions
to prevent calling `projectile-acquire-root` twice.
When running one of those functions (e.g. projectile-run-vterm) from a folder outside a projectile root (e.g. my home folder) I was being ask twice in the minibuffer to provide a projectile project root. This was caused because projectile-acquire-root was being called twice without setting the default folder.
Thanks!
> Do not ask twice for project running ielm, term and vterm

- projectile.el
Current type declaration of `projectile-project-search-path` is showing a type mismatch error in Customize with the default value `nil`. This PR fixes this issue.
Thanks!
> Fix projectile-project-search-path defcustom type

- CHANGELOG.md
- projectile.el
Add "-B" arguments to maven commands
Thanks!
> Use "mvn -B" when compiling or running tests in maven projects to avoid ANSI coloring clutter and fix #1647

- CHANGELOG.md
- projectile.el
When prefix arg is supplied and a directory is selected, the directory
passed to projectile-dir-files is not necessarily the project root, so
using projectile-expand-root yields incorrect behavior.
For example, in a project rooted at `~/project` with files:
```
~/project/
~/project/Makefile
~/project/foo/bar.c
```
With `C-u M-x projectile-replace-regexp`, selecting directory `~/project/foo/`, projectile incorrectly attempts to read file `~/project/bar.c`, resulting in an error.
Thanks!
When running `eldev test`, I see that two tests fail, but they also fail in master, so I don't think it has anything to do with this PR.
> Fix file paths in projectile-replace* with prefix arg

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
Hi! This PR adds a convenience function for changing the properties of a project type that is already registered. The use case would be if you only want to change one parameter and keep the others as they already are. Example usage:
```elisp
(projectile-update-project-type
'sbt
:related-files-fn
(list
(projectile-related-files-fn-test-with-suffix "scala" "Spec")
(projectile-related-files-fn-test-with-suffix "scala" "Test")))
```
Before I was editing `projectile-project-types` manually, so I hope this change is useful if there is not already a nice way to do this.
Thanks!
> Add a Function for Updating the Properties of an Existing Project Type

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Fix rediscovery in `projectile-clear-known-projects`.
> Fix rediscovery when clearing known projects

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
This adds project detection for unpacked Debian source packages. We detect
this type by the presence of a debian/control even though technically we
should probably check for all of debian/{rules,contro,changelog}. I found
documenting this too cumbersome so I went with just the control file.
In Debian there's two main (lightweight) ways of building packages:
dpkg-buildpackage and debuild. The latter is pretty much just a wrapper for
the former that also runs static checks across the resulting package.
Developers usually use debuild so that's what we use here. The -uc -us
options we hardcode are extremely common. They disable codesigning which
you'd usually not want to do for a simple developmnet build since it can
always be done using debsign before uploading the package.
Since tests …
> Add project detection for Debian packaging directories

- projectile.el
#1657 seemed to cause some problems. It passes a string, instead of a list of strings or a function, as the marker-files parameter to projectile-register-project-type, which, when opening a project-file gave me this:
```
Debugger entered--Lisp error: (wrong-type-argument stringp 100)
expand-file-name(100 "/home/jeh/code/gitlab/jehelset/projectile-cmake/")
projectile-expand-root(100)
(file-exists-p (projectile-expand-root file))
projectile-verify-file(100)
apply(projectile-verify-file 100)
#f(compiled-function (&rest cl-x) #<bytecode 0x15936a79d645>)(100)
mapcar(#f(compiled-function (&rest cl-x) #<bytecode 0x15936a79d645>) "debian/control")
cl-mapcar(#f(compiled-function (&rest cl-x) #<bytecode 0x15936a79d645>) "debian/control")
apply(cl-mapcar #f(compiled-function (&rest cl-x) #<bytecode …
```
> Fix debian packaging directory registration.

- CHANGELOG.md
- doc/modules/ROOT/pages/configuration.adoc
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
Support configuring, building and testing CMake projects using [cmake-presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html).
Introduces `projectile--cmake-command` for CMake projects which computes a command based on the command-type. If CMake preset support is enabled through the `projectile-enable-cmake-presets` custom, and if presets are supported for the command-type by CMake, CMake preset-files are parsed and a completing-read is done on the names of the command presets along with an option for manual configuration. If not supported, or there are no presets specified for the given command-type, it reverts to manual configuration as before. Configure, build and test commands for CMake projects are all implemented in terms of this command.
To support presets the …
> Add support for CMake-presets.

- projectile.el
This commit adds:
- install - which runs "raco pkg install" to insatll the current package
- package - which runs raco pkg create --source X
where X is the absolute path to the current package directory
Signed-off-by: Maciej Barć <xgqt@riseup.net>
> update racket project type with :install and :package

- CHANGELOG.md
- projectile.el
Hi @bbatsov 
I would like to add a PR to fix #1637. Could you have a look?
Thanks
Thanks!
> [Fix #1637] Integrate with savehist-mode

- projectile.el
Use mapc for side-effects only function.
Leverage directory-files-no-dot-files-regexp to filter out dot files.
No sorting is required in project discovery.
Thanks!
> Refactor projectile-discover-projects-in-directory

- CHANGELOG.md
- projectile.el
Correct CMake system-preset filename
Had used the wrong filename for the CMake system-preset-file. Fix according to https://cmake.org/cmake/help/git-stage/manual/cmake-presets.7.html.
Thanks!
> [Fix #1673] Correct CMake system-preset filename.

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
Hi :wave:, this PR is a proposed solution to https://github.com/bbatsov/projectile/issues/1650, achieved by allowing the `:test-dir` option to take a function which returns the test directory given the implementation directory.
The behaviour for the project in https://github.com/bbatsov/projectile/issues/1650 with the config:
```elisp
(setq projectile-create-missing-test-files t)
(projectile-update-project-type
'sbt
:test-dir
(lambda (file-path) (projectile-complementary-dir file-path "main" "test")))
```
Is that calling `projectile-toggle-between-implementation-and-test` from `src/main/scala/bar/package.scala` sticks you in `src/main/scala/bar/packageSpec.scala` and calling from `src/test/scala/foo/package.scala` sticks you in `src/test/scala/foo/packageSpec.scala` (regardless of either …
> Allow Functions for :test-dir

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
Hi! This PR is a follow up to https://github.com/bbatsov/projectile/pull/1671, it allows the `:src-dir` property of projects to be set to a function like `:test-dir` was in the previous PR.
Similar to to `:test-dir`, when `projectile-toggle-between-implementation-and-test` is called and the user is in a test file, and it's determined a project type has it's `:src-dir` property set to a function, this function will be called to obtain the directory in which the implementation file of the corresponding test file resides.
The result is that from the project in #1650 with the config:
```elisp
(setq projectile-create-missing-test-files t)
(projectile-update-project-type
'sbt
:src-dir
(lambda (file-path) (projectile-complementary-dir file-path "test" "main"))
:test-dir
(lambda (file-path) …
```
>  Allow Function for :src-dir

- CHANGELOG.md
- doc/modules/ROOT/pages/usage.adoc
- projectile.el
Extend type of `projectile-project-search-path` to allow elements of
form (DIRECTORY . DEPTH) to discover projects at the specified depth.
Thanks!
> [Fix #1500] Add support for recursive project discovery

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
The commands `async-shell-command` and `shell-command` accept up to three parameters:
`COMMAND &OPTIONAL OUTPUT-BUFFER ERROR-BUFFER`, the commands `projectile-run-shell-command-on-root` and `projectile-run-async-shell-command-on-root` (which call those commands above) are not callable non-interactively and can't pass the two optional parameters to the `(async)-shell-command`.
Change the signature of these two functions to match the `(async)-shell-command`:
```lisp
(defun projectile-run-shell-command-in-root (command &optional output-buffer error-buffer)
...)
(defun projectile-run-async-shell-command-in-root (command &optional output-buffer error-buffer)
...)
```
* So they can be now called directly from an elisp code.
* **It is important to emphasize that the interactive call behaves …
> Add opt params to projectile-run-(async)-shell-cmd

- CHANGELOG.md
- projectile.el
Dissect TRAMP file names and use TRAMP aware shell function.
Make sure that ctags uses relative paths names: This also makes
workaround for #1377 obsolete.
Thanks!
> [FIX #1550] Make projectile-regenerate-tags tramp-aware

- projectile.el
This fixes byte compilation warnings on Emacs 28.
This also fixes Eldev Github Actions for `emacs-snapshot`.
> Limit custom variable docstring length to 80 characters

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
Hi,
This is my first PR here, I'm trying to follow the guidelines but I apologize in advance if I'm doing something wrong. I have not updated the readme or docs yet because I haven't found a suitable place to put my change and I didn't want to change the wrong files.
This is a very simple change that leverages Emacs' `compile` command argument to allow for interactive compilation buffers. This is particularly useful when using `projectile-project-run-cmd`, as it allows you to interact with your program.
Thanks!
> Add projectile-comint-mode variable to allow for interactive compilation buffers

- projectile.el
compilation-mode keeps track of the "current" directory in the output by
matching on messages such as make's "Entering directory ...", when this
happens the 'directory' variable is set, but the current code just ignores
it when checking whether we should search across project directories or
not. This means that in cases when the filename is actually unambigous
relative to the given directory we'll still go off and try to find it all
over the project which is less than ideal.
Instead of re-implementing the correct directory logic here we refactor
compilation-find-file-projectile-find-compilation-buffer to locally append
our project directories to the the global compilation-search-path and let
the real compilation-find-file fun do it's thing.
While this makes the behaviour more consistent …
> Fix compilation-find-file advice handling of directory

- projectile.el
See #1500.
Now you can add a directory DIR to `projectile-project-search-path` with
depth 0 to mean that if DIR is a project then add it to projectiles
project list.
This was already taken care of by #1680.
Thanks!
> Allow recursive project searches to add a directory explicitly

- CHANGELOG.md
- projectile.el
fix #1514
Hi👋
I fixed `projectile-ag` global ignores not in effect!
```el
(setq projectile-globally-ignored-directories '("node_modules"))
(setq projectile-globally-ignored-files '("baz"))
(projectile-ag "bar")
```
↓output contain ignore file, directory
```
ag --ignore baz --ignore node_modules/ --literal --group --line-number --column --color --color-match 30\;43 --color-path 1\;32 --smart-case --stats -- bar .
```
```el
(setq projectile-globally-ignored-directories nil)
(setq projectile-globally-ignored-files nil)
(projectile-ag "bar")
```
↓output
```
ag --literal --group --line-number --column --color --color-match 30\;43 --color-path 1\;32 --smart-case --stats -- bar .
```
by …
> [Fix #1514] Fix projectile-ag global ignores not in effect

- doc/modules/ROOT/pages/configuration.adoc
- projectile.el
Fix #1517 
continue #1535 PR
I made it easy to per-project compilation buffer configures!
To make per-project  compilation buffer, currently require user set:
```emacs lisp
(setq compilation-buffer-name-function
#'projectile-compilation-buffer-name)
(setq compilation-save-buffers-predicate
#'projectile-current-project-buffer-p)
```
Proposing changes can set:
```emacs lisp
(setq projectile-per-project-compilation-buffer t)
```
- Easy to set.
- Do not affect the other packages compilation buffer.
Thank you!
Thanks!
> [Add #1517] Add per-project compilation buffer variable

- projectile.el
This prevents the unintentional addition of project subdirectories if
the directory tree layout does not match the specified
`projectile-project-search-path`.
Thanks!
> [Fix #1701] Always add project root to known projects

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
This change adds support for detecting Nix flakes, a new way of managing Nix projects.
See https://nixos.wiki/wiki/Flakes
> Add project detection for Nix flakes

- projectile.el
- test/projectile-test.el
* Use fd/fdfind when available
* Strip leading ./ from paths produced by find
> [Fix #1703] Improve projectile-generic-command default

- projectile.el
- test/projectile-test.el
Fix #1709
If `projectile-project-buffer-p` is executed for a non-current project, `default-directory` return current directory.
Since `projectile-project-buffers` contains current buffer, kill current buffer unintentionally.
`default-directory` → `(file-name-directory buffer-file-name)`
Seem to it works correctly. 
→ not working https://github.com/bbatsov/projectile/pull/1713#issuecomment-930844738
If `buffer-file-name` is nil, use `default-directory`.
- `C-u` `projectile-switch-project` {select project}  `k` 
not contain current buffer✔
Thanks!
> [#1709] Fix `projectile-project-buffer-p` contain current buffer

- CHANGELOG.md
- projectile.el
By using `read-shell-command`.
Fixes #1692 .
> Allow completions for projectile-run{-async,}-shell-command-in-root

- projectile.el
I had a misconfiguration where my cache-file variable was pointing to nowhere (actually not even the parent folder was there, so the file was also not createable which leads `file-writeable-p` to always return false).
The cache was always invalid and recalculated, because the file was not there
and `projectile-maybe-invalidate-cache` would always call `projectile-invalidate-cache`.
With this patch at least a warning is printed to `*Messages*` that something is not quite right.
- [-] You've added tests (if possible) to cover your change(s)
- [-] The new code is not generating bytecode or `M-x checkdoc` warnings
- [-] You've updated the …
> Show a warning if the projectile cache is not writable

- projectile.el
If the search path is the root of a volume, it can have a spotlight
directory in it that emacs can't necessarily read. This avoids errors
like this:
```
Opening directory: Operation not permitted, /home/offby1/workspace/.Spotlight-V100
```
---
Thanks!
> Ignore errors listing directory files in the project search path

- CHANGELOG.md
- projectile.el
GNUMakefile is valid name for GNU Make.
This patch add project definition to detects gnumake project from GNUMakefile.
Thanks!
> [Fix #1718] Add a project definition for GNUMakefile

- CHANGELOG.md
- projectile.el
My first attempt to touch emacs packages, so please let me know if I messed something up.
Make `projectile-discover-projects-in-directory` interactive to fix #1714 
Tested this locally and it seems to bring back the old-functionality back where one can set the root-dir where to  find projects.
Thanks!
> Make projectile-discover-projects-in-directory interactive

- CHANGELOG.md
- projectile.el
Fixes #1731 and also speeds up performance because `projectile-bookmarks.eld` don't have to be merged for every project found in `projectile-project-search-path`:
Benchmarking master:
```
(benchmark 1 '(projectile-discover-projects-in-search-path))
Elapsed time: 28.751600s (7.017759s in 99 GCs)
```
This commit:
```
Elapsed time: 2.622743s (0.502195s in 7 GCs)
```
Thanks!
> [Fix #1731] Only discover NEW projects in search path

- projectile.el
Don’t assume internal format of Emacs timestamps.
They are documented to change in a future version.
This patch works on older Emacs versions; it can be simplified
to just use time-convert if we assume Emacs 27 or later.
> Port projectile-time-seconds to future Emacs

- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
Hi!  This PR is in response to a discussion in https://github.com/bbatsov/projectile/issues/1650#issuecomment-987977517, basically it's a fix for the `src-dir` and `test-dir` properties being prematurely circumvented if they are set to strings when switching from/to test/impl files.  Essentially the function for finding a test/impl file using `src-dir` and `test-dir` (set as strings) was called in `projectile--find-matching-test`, but a fallback already existed in `projectile-find-implementation-or-test` which was being used in preference.
This PR hopes to fix and simplify the above by making impl/test switching wholly contained in `projectile--find-matching-file`/`projectile--find-matching-test`.
I've also updated the doc tweaking the `src-dir`/`test-dir` as a function example since I …
> Make projectile--find-matching-test Use src-dir/test-dir Properties

- CHANGELOG.md
- projectile.el
Adds support for preset-based installs in CMake-projects as suggested in https://gitlab.kitware.com/cmake/cmake/-/issues/23117#note_1137638.
Thanks!
> Add support for preset-based installs in CMake projects.

- projectile.el
The byte compiler in Emacs 28 show warnings for "docstring wider than 80 characters" in multiple places. These warnings are show every time the package is updated from list-packages so it's visible for the user.
I mostly just used fill-paragraph to fix these docstrings.
> Fix wide docstrings

- CHANGELOG.md
- projectile.el
The unescaped periods were causing unexpected directories to be ignored.
E.g. for the following go project, the configitem directory was ignored because it matched the regex ".git":
```
$ find pkg -type f
pkg/metrics/argus.go
pkg/secrets/secrets.go
pkg/dynamo/dynamo.go
pkg/utils/types.go
pkg/utils/utils.go
pkg/utils/errors.go
pkg/configitem/configitem.go
pkg/api/handlers.go
pkg/api/middleware.go
```
Thanks!
> Escape periods in "projectile-globally-ignored-directories"

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Hi, this is a proposed fix for #1765, it (re) adds a default value for the `src-dir` and `test-dir` properties for project types (= `"src/"` and `"test/"`).  The main effect is for `projectile-toggle-between-implementation-and-test`, so these defaults will be used as a fallback if no other method can be found for finding an impl/test file.
There was a breaking change in https://github.com/bbatsov/projectile/pull/1734 (sorry!) which removed this fallback, so project types without a `src-dir` or `related-files-fn` property wouldn't have a method for finding corresponding test/impl files, as shown in #1765.  This fallback is not always particularly useful however, for example when your implementation file doesn't contain `"src/"`, this PR throws an error in such cases.
I've also tweaked some …
> Resurrect Default src-dir and test-dir for project-types

- projectile.el
Change Grails app configure file name to application.yml
**As per grails new version (version 4 and 5), the configuration file name has been change to application.yml from application.properties**
Thanks!
> Change Grails app configure file name to application.yml

- projectile.el
hi👋
Fix byte compile error https://github.com/bbatsov/projectile/runs/6076691588?check_suite_focus=true
`projectile.el:850:22:Error: ‘(let ((version (or (projectile--pkg-version) projectile-version))))’ is a malformed function`
Thanks!
> Fix byte compile error

- .github/workflows/test.yml
Now that Emacs 28.1 is released and the latest stable version available, we should include testing with this version in CI.
Thanks!
> Add Emacs 28.1 to CI tests

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Hi, this PR makes it so that duplicate commands are not added to the command history (a command is only added to the history ring if it doesn't equal the most recent command).  
Related is: https://github.com/bbatsov/projectile/issues/1654, but it has the same effect for `projectile-test-project`, `projectile-compile-project` and so on.
Thanks!
Thanks!
> Don't add Duplicate Commands to Command History

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
For a CMake-project with a preset-driven workflow, the caching of commands is not necessary (https://github.com/bbatsov/projectile/issues/1676). This PR adds functionality for disable caching.
We add a variable `projectile-project-enable-cmd-caching` so that the user can enable or disable caching on a per-project basis by setting this variable in `.dir-locals.el`. If the variable is set to `nil`, then `nil` is passed as command map to `projectile--run-project-cmd` so that no commands are cached. The variable is `t` by default.
The variable is checked with a function `projectile--cache-project-commands-p` which ensures that directory local variables for the project are loaded.
I didn't update the readme, but dropped a line in `projects.adoc`.
Before submitting a PR make …
> Add variable to enable or disable command caching.

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
When `projectile-project-root` was unable to find a project root for a
directory, it would not cache the negative result, so future invocations would
repeat the (often expensive) search for a project root every time.
With this change, `projectile-project-root` caches failure to find a project
root, when that failure is expected to be permanent, and consults that cache
for speed on subsequent invocations.  "Expected to be permanent" means that
either we're trying to find the project root of a local directory, or we're
successfully connected to a remote directory via TRAMP.  If the directory isn't
local, but we can't connect to it, we consider that a transient failure and
don't cache it.
Under the hood, this change uses the same `projectile-project-root-cache`
that's used to cache …
> [Fix #1755] Cache failure to find project root

- CHANGELOG.md
- projectile.el
Rails puts most of its source files under app rather than lib. This
updates the src-dir to allow easy switching between source and test
files in this case.
Thanks!
> Switch rails-rspec src-dir

- projectile.el
As I describe in #1783, the function `projectile-dir-files-alien` is not returning the same value in macOS as the function `projectile-dir-files-native` because it returns values with a leading "./". This PR fixes this, ensuring both functions return values without a leading dot directory and fixing the issue reported in https://github.com/doomemacs/doomemacs/issues/6504.
> Fixes projectile-dir-files-alien on macOS

- CHANGELOG.md
- projectile.el
It is so common for a Go-based project to have a Makefile.
> Give the project type "go" higher precedence than universal types

- CHANGELOG.md
- projectile.el
Discovering  a deep recursive directory structure  can take a while to finish. 
Inform user about the progress so the user can estimate remaining time
and clearly see that Emacs is busy working, not hung.
> Add a progress reporter to recursive progress discovery

- projectile.el
I saw some byte comp docstring errors on the snapshot CI, I think this PR should fix them :slightly_smiling_face: 
EDIT: alright looks to have passed :slightly_smiling_face: 
-------------------------------
Thanks!
> Fix Doc Errors on Emacs Snapshot

- CHANGELOG.md
- projectile.el
Hi, this PR adds src-dir and test-dir Properties to the mill Project Type (see https://com-lihaoyi.github.io/mill/mill/Common_Project_Layouts.html), so this should help with default test/implementation toggling etc.
Thanks!
> Add src-dir and test-dir Properties to mill Project Type

- doc/modules/ROOT/pages/configuration.adoc
This PR fixes a small grammar mistake on the docs/configuration page
Thanks!
> docs/configuration: Grammar nit

- CHANGELOG.md
- doc/modules/ROOT/pages/configuration.adoc
- projectile.el
Hi,
I created this PR to enable users to select file name pattern and extension when performing `projectile-replace` with `C-u`.
This is to prevent `projectile-replace` from searching on very large files of a project (my Emacs hangs when projectile search on a 1MB Javascript library file, while I only wanted to search and replace on Rust code).
Currently, the file extension filtering is supported only by `ag` (using the option `-G <file-ext-pattern>`). 
I don't use `rg`, hence I haven't been able to add the corresponding option for it (and also for `ack` and `grep`).
Can you take a look and advise if this PR can be merged?
Thank you!
- ~~[ ] You've …
> Support `projectile-replace` to select file extension on C-u

- README.md
- projectile.el
Update readme and projectile.el with the minimal version of `fd` supported by projectile.
Issue ref - https://github.com/bbatsov/projectile/issues/1788
p.s.
I haven't updated the changelog file since there are no changes really. Let me know if I should do so.
> Fix #1788: Add notes about minimal version of `fd`

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
Hi!  This PR adds variables intended to be used to be used as local overrides (in the same vein as https://docs.projectile.mx/projectile/projects.html#configure-a-projects-lifecycle-commands) for the project type attributes test-prefix, test-suffix, related-files-fn, src-dir and test-dir.  The intention is that you would no longer have to register a custom project type and set `projectile-project-type` in your `.dir-locals.el` just because you want to override say the test suffix for one particular project.
Thanks!
Thanks!
> Add Local Overrides for more Project Attributes

- CHANGELOG.md
- projectile.el
This closes #1708. This is a small behaviour change to make the behaviour consistent across different methods of searching files. The issue raised was on how `projectile-ripgrep` did not search through hidden files, while `projectile-grep` does. This also still respects the `.gitignore` and the various excluded directories, so the only change is that it now includes non-specifically excluded hidden files.
Interestingly enough, the behaviour behind using the different ripgrep libraries `rg` and `ripgrep` were actually different here, where `rg` would include hidden files while `ripgrep` would exclude them.
----------------
Thanks!
> [Fix #1708] Search hidden files with projectile-ripgrep

- CHANGELOG.md
- projectile.el
Task is a task runner.
go-task/task support multile file name (Taskfile.yml, Taskfile.yaml, Taskfile.dist.yml, Taskfile.dist.yaml), but this patch just support Taskfile.yml for now.
Reference: https://taskfile.dev/
Thanks!
> Add support go-task/task

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
1. projectile-open-projects should gets a list of buffers like `projectile-project-buffers`.
2. Make it possible to ignore special project buffers
Closes #1754.
Closes #1804.
Thanks!
> [Fix #1754] `projectile-open-projects` lists projects for which all buffers are closed

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
Functions projectile-add-dir-local-variable and projectile-delete-dir-local-variable
wraps their built-in counterparts. They always use `.dir-locals.el` from root of projectile project.
Thanks!
> Add helpers for dir-local-variables for 3rd party use

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
(projectile-project-type DIR) should return the right project type.
(projectile-project-type DIR) sometimes return the wrong project type
The problem is, some logic branches inside `projectile-project-type` involve calling 
`(projectile-detect-project-type)` which use the `default-directory` instead of the DIR we supply.
1. Amend `projectile-detect-project-type` to take optional argument DIR(just like `projectile-project-type`).
2. Pass along the input from the projectile-project-type to `projectile-detect-project-type`
Let DIR1 and DIR2 be 2 directories from projects of different types
Call (projectile-project-type DIR2) from a DIR1, you will get DIR1's project type instead of DIR2's(given that DIR2's project type is not cached)
```
Projectile 2.6.0-snapshot
```
GNU Emacs 29.0.50 (build …
> Projectile-project-type could return the wrong project type when called with argument

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Previously, the directory it found would depend on the order of
`projectile-project-root-files-bottom-up` (or the provided list).
given a directory structure
```
foo
├── .a
└── bar
└── .a
└── baz
└── .b
```
`(projectile-root-bottom-up ".../foo/bar/baz/" '(".a" ".b"))` would return
`".../foo/bar/"`, because the current definition looks for any `".a"` before it
looks for ".b".
With this change, it traverses the directory structure once, looking for any
element of the list before moving up a level. So now the same call returns
`".../foo/bar/baz/"`, which matches the documented behavior of returning the
bottommost matched directory.
Fixes #1796
Thanks!
> Find project files bottom-up

- CHANGELOG.md
- projectile.el
Prioritizes .projectile above other bottom-up root files.
Also makes the name of .projectile customizable.
Related to #1810.
Thanks!
> Add a projectile-root-marked function for finding roots

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
Some project types can have different project files name patterns (for example, dotnet projects can have `csproj` or `fsproj` depending on whether they're written in C# or F#)
Related to those two examples, sometimes the project-file does not have a constant name. A C# project named `Foo` will have a project-file named `Foo.csproj`. 
This PR allows project type registrations to specify wildcards for their filenames (like `"*.csproj"`) and multiple project-file specs (like `'("*.csproj" "*.fsproj")`).
I've added some tests to make sure this works and keeps working as expected, and adjusted the type registrations for dotnet projects which benefit directly from this feature.
by checking …
> Allow multiple project-files per project type, allow wildcards in the project-file specs

- CHANGELOG.md
- projectile.el
Hi there, 
This PR add support for [PEP621](https://peps.python.org/pep-0621/) python projects, by detecting the standardized `pyproject.toml` file.
I must admit that I am not confortable with the eldev test framework, and I could not find out if and how i could write a test for this new setup. 
Thank you for all the work on this essential package.
- ~~[ ] You've added tests (if possible) to cover your change(s)~~
- ~~[ ] You've updated the readme (if adding/changing user-visible functionality)~~
Thanks!
> feat: add python PEP621/PEP5128 support

- CHANGELOG.md
- projectile.el
Elm has a standardized project hierarchy and it's missing from projectile creating this kind of issues: https://github.com/emacs-lsp/lsp-mode/issues/3936
Fixes https://github.com/emacs-lsp/lsp-mode/issues/3936
Thanks!
> Elm project type added

- projectile.el
Upon starting to use `projectile-compile-project`, currently the only
way to find out how to set default command is to look at the
code. Let's mention the necessary variable in the function docs instead.
Thanks!
> Mention how to set default cmd to (projectile-compile-project)

- projectile.el
opens Vterm in other window instead of opening in the same window while invoking Vterm with `projectile-run-vterm`
> Make projectile-run-vterm open vterm in other window

- CHANGELOG.md
- projectile.el
[https://github.com/nim-lang/nimble](Nimble) is the default package manager for Nim programming language projects. They were being picked up as .NET projects due to `src/` being present.
---
~~- [ ] You've updated the readme (if adding/changing user-visible functionality)~~
> Detect Nimble projects for Nim programming language

- CHANGELOG.md
- README.md
- doc/modules/ROOT/pages/faq.adoc
- doc/modules/ROOT/pages/usage.adoc
- projectile.el
When fd is installed, use it with appropriate options instead of git ls-files in order to fix https://github.com/bbatsov/projectile/issues/1148.
Thanks!
> [#1148] Don't show deleted files in listing

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
Julia projects were getting detected as `dotnet-sln`. This template follows the structure created by [PkgTemplates.jl](https://github.com/JuliaCI/PkgTemplates.jl) which is pretty standard, so I didn't bother to be more specific than `julia`.
I also added a Julia detection test and another that confirms only a `src` dir present matches a .NET solution.
~~- [ ] You've updated the readme (if adding/changing user-visible functionality)~~
> Detect Julia projects

- CHANGELOG.md
- projectile.el
`projectil-complementary-dir` was using `replace-regexp-in-string` allowing case manging during the replacement. That's not what we want here. See #1847
Fixes: #1847 
Thanks!
> Use literal directory name casing during impl / test toggle

- CHANGELOG.md
- projectile.el
Uses the existing `projectile-test-directory` function when looking up test directory (and right beside these are calls looking up the src-dir attribute that should also be using the existing `projectile-src-directory` function.
Note, that this seems to require the trailing slash on the `projectile-project-test-dir` value. I'm not sure if that is OK. It seems consistent with what is declared in the various project types, but is not mentioned in the variable documentation.
Fixes #1839
Thanks!
> Obey `projectile-project-test-dir` (and similarly for src dir) when toggling between impl and test

- CHANGELOG.md
- projectile.el
Very small PR to add ripgrep as a method to the projectile commander just like Ag is.
No tests added, because I didn't see any suitable tests for commander or Ag.
On the choice of keybinding: I'd prefer `r` but that's already taken and I don't want to introduce a breaking change. The 'p' in 'ripgrep' stands out phonetically so it seemed the best choice to me. Any lower case character would do, I guess.
Changelog not yet adjusted. Would wait for a PR/issue ID to reference.
> Add ripgrep as a commander method.

- CHANGELOG.md
- projectile.el
Currently fd uses auto mode which inserts colors when used over tramp.
Thanks!
> fd: explicitly disable colors

- CHANGELOG.md
- projectile.el
Yarn and pnpm are two popular alternatives to npm and you can tell which is used in a project by the existence of their respective lock files.
Plus, the `build` script is worth being a default "compile" command for npm-based projects.
> Add project types "yarn" and "pnpm" separate from "npm"

- projectile.el
I use conan dependency manager to setup c++ cmake project. It creates/modifies CMakeUserPresets.json by adding includes to generated CMakePresets.json files. The problem is that projectile does not follow those includes when parsing presets files.
Warning: this is my first ever PR in elisp.
No, but no cmake related code is testes or I was unable to find any tests.
No, I had one error but I also had it without my changes.
Had many warnings but non related to new code.
Not sure if this change qualifies for last two checkboxes.
> Follow includes in CMake files

- CHANGELOG.md
- projectile.el
This's a small fix to allow reopening an existing vterm buffer in other window. Changed the behavior to check if there's an existing buffer and take into consideration the `other-window` indication and do the switching accordingly.
> [Fix #1835] Reopening existing vterm buffer in other window

- CHANGELOG.md
- projectile.el
> [Fix #1853] `projectile-generic-command` should use `projectile-fd-executable` to find the path for fd

- CHANGELOG.md
- projectile.el
Adds support for package commands in cmake-projects. Both preset and non-preset version included.
Thanks!
> Add package command for CMake.

- projectile.el
Prior to emacs 28, the `project.el` package did not provide `project-root`.  By providing an overload for `project-root`, any compatibility checks of `(fboundp 'project-root)` done by other packages will return true, even for versions that do not have `project-root`.
Fixes https://github.com/bbatsov/projectile/issues/1868.
- [NA] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [NA] You've updated the readme (if adding/changing user-visible functionality)
Thanks!
> Check for project-root before adding overload

- projectile.el
Hi!  `mill all __.xyz` is no longer supported, simply removing `all` should be equivalent, and also work on older versions.
Thanks!
Thanks!
> Remove 'all' from the mill project type's compile and test commands

- CHANGELOG.md
- doc/modules/ROOT/pages/faq.adoc
- doc/modules/ROOT/pages/projects.adoc
- doc/modules/ROOT/pages/usage.adoc
- projectile.el
This PR adds support for detecting projects using [Sapling VCS](https://sapling-scm.com/).
Sapling is a Meta maintained fork of Mercurial. It uses `.sl` as the state directory instead of `.hg` to avoid compatibility issues with Mercurial. See this page for comparison with Mercurial: https://sapling-scm.com/docs/introduction/differences-hg
**Testing**
1. Load projectile with changes from this PR
2. Open a project managed with Sapling
3. Run `M-x projectile-project-info`:
4. Run `M-x projectile-find-file`:
Thanks!
> vcs: add Sapling support

- CHANGELOG.md
- doc/modules/ROOT/pages/faq.adoc
- doc/modules/ROOT/pages/projects.adoc
- doc/modules/ROOT/pages/usage.adoc
- projectile.el
Support for detecting  [Jujutsu](https://martinvonz.github.io/jj/) projects.
[Jujutsu](https://github.com/martinvonz/jj) is a VCS  which designed to working with multiple backend. Jujutsu is designed so that the underlying data and storage model is abstract. Today, it features two [backends](https://martinvonz.github.io/jj/latest/glossary#backend)—one of them uses a Git repository for storage, while the other is a native storage backend[1](https://github.com/bbatsov/projectile/pull/1876#user-content-fn-native-backend-2510681dc52b19e0675a59b0446e2fec).
*It also  planed to replace Mercurial as an internal monorepo client at Google. (See the [slides](https://docs.google.com/presentation/d/1F8j9_UOOSGUN9MvHxPZX_L4bQ9NMcYOp1isn17kTC_M/view))
**Testing**
Manually verified that …
> vcs: add Jujutsu support

- projectile.el
Hi, Sorry, i made mistake on my previous PR #1876
Didn't push latest change :( .
For correctly parsing file list, This PR added  piped shell command `tr '\\n' '\\0` to `projectile-jj-command` 
Thanks!
> Fix `projectile-jj-command`

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
Hi!  This PR adds new custom variable `projectile-cmd-hist-ignoredups`, which can be used to tweak how duplicates are dealt with in projectile's command history.  The custom variable is more or less identical in behaviour to `eshell-hist-ignoredups`.
Specifically, the existing default behavior is maintained with the value of `t`, which means consecutive duplicates are ignored.  A value of `'erase` means only the last duplicate is kept, whilst a value of `nil` means all duplicates are kept.
(PR is an iteration on https://github.com/bbatsov/projectile/pull/1774)
Thanks!
> Add new custom variable 'projectile-cmd-hist-ignoredups'

- CHANGELOG.md
- projectile.el
projectile-recentf-files expands recentf files to use canonicalized versions, /home/example/project instead of ~/project. However, if the project is not active and projectile-recentf was called, it would return non-canonicalized directory which then fails the comparison with recentf list.
Thanks!
> Fix projectile-recentf with inactive project (#1881)

- projectile.el
- test/projectile-test.el
When running the projectile tests locally I noticed that my top-level
`.dir-locals.el` file would get a `fooo . 1` added to it.
Modify the test `projectile-add-dir-local-variable` such that it
creates its own `.dir-locals.el` file which it can modify. This was a
little bit finicky because `projectile-add-dir-local-variable` doesn't
restore the selected window and buffer after executing so I've fixed
that function to restore the windows as they were beforehand. When
applying a similar fix to the `...delete...` function I had to improve
that test as well
Thanks!
> Fix tests to not modify top level .dir-locals.el file

- projectile.el
I added the metadata only to the default Emacs `completing-read`. as I am not familiar with the 3rd party systems helm and ivy.
I'm not sure about checking the last 2 checkboxes. The changes are only ***visible*** if using third-party packages like
[marginalia](https://github.com/minad/marginalia) and [embark](https://github.com/oantolin/embark) which use the metadata.
`projectile-switch-project` without metadata:
with metadata:
> Add category metadata to completing-read

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
I originally created #1879 but have since deleted that GitHub account,
as such the associated repository and pull request were closed. The
new version of that PR can be found at #1894.
This PR implements Solution 2 as described in #1894.
There are certain modes for which the
`projectile-find-file-hook-function` function does not run by
default. This includes, `shell`, `eshell`, and `magit`. If one
navigates directly to one of these buffers and calls
`projectile-relevant-known-projects` while
`projectile-current-project-on-switch` is set to `'keep` they will
notice that the first repository in the list is not the one that they
expect
There are two possible solutions that come immediately to mind. I
want to mention both of them for consideration though naturally
this PR only implements one …
> Add #'projectile-track-known-projects-find-file-hook to 'buffer-list-update-hook

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
Add support for the [xmake](https://xmake.io) build utility. 
Thanks!
> Add support for xmake build utility

- projectile.el
project-file is a more suitable category for the completion (also used by project.el).
'vertico-prescient-completion-category-overrides changes the completion style for 'file to '(basic partial-completion) and limits completion to prefix matches.
Fixes #1902
Thanks!
> Use 'project-file as category metadata in completing read

- .github/workflows/test.yml
This will fix the following warning:
"The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. [...]"
Thanks!
I think most tasks above do not apply for CI changes. Let me know if I'm wrong.
> Upgrade actions/checkout to v4

- CHANGELOG.md
- projectile.el
- test/projectile-test.el
-------
The presence of an "src/" directory doesn't say anything about the
type of the project. This PR fixes the dotnet sln project type to rely
on the presence of an .sln file instead of the "src/" directory.
Thanks!
> Fix dotnet sln project type

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
- test/projectile-test.el
This PR adds Zig project discovery.
Thanks!
> Add Zig project discovery

- doc/modules/ROOT/pages/projects.adoc
First attempt at expanding the table of file markers for projects based on code at [master/projectile.el#L3441](https://github.com/bbatsov/projectile/blob/master/projectile.el?rgh-link-date=2024-10-22T08%3A55%3A41Z#L3441)
I've followed the order of the languages/files in `projectile.el` (I hope!).
Not sure descriptions under `Project Type` are 100% correct so happy to revise anything that needs changing.
Thanks!
> Expands table of files for project markers

- projectile.el
The `jj files` command was deprecated and replaced with `jj file list` in Jujutsu 0.19 and is slated to be fully removed in the future
Thanks!
> Replace deprecated Jujutsu command

- CHANGELOG.md
- doc/modules/ROOT/pages/projects.adoc
- projectile.el
Add support for swift projects using swift package manager (SPM).
The 'swift-spm symbol is qualified to leave room for other flavors of swift project that are more Xcode oriented or use cocoapods.
Thanks!
> feat: add support for swift projects

- projectile.el
**Bloop file is always present in Home Directory**
Hey Bbatsov, love all of your work. I was having an issue with my home directory being indexed on multiple computers, and I couldn't figure out why until I manually went through and checked against all of the `projectile-project-root-files`, since I checked against the obvious suspects and couldn't find it.
Anyway, the culprit was a `.bloop` directory in my home directory, so I checked on why this was there. According to the Bloop [documentation](https://scalacenter.github.io/bloop/docs/server-reference), this is where the bloop server places its config by default.
This was the most obvious solution to me, which is to remove this by default, since mill and sbt projects are already covered. 
Before submitting a PR make …
> Remove Bloop from Project File List

- projectile.el
Hi, this PR adds `build.mill` as a project file name for the mill project type, it seems to be the recommended extension now, see https://mill-build.org/mill/scalalib/intro.html.
Thanks!
> Add build.mill as a project file name for the mill project type

- doc/modules/ROOT/pages/projects.adoc
Bloop is a Scala build tool, not a Clojure tool: https://scalacenter.github.io/bloop/
> Fix docs: .bloop for Scala, not clojure

- projectile.el
The method `projectile-add-known-project` does not have a kbd, nor it shows in the menu
Add kbd for projectile-add-known-project
Add menu entry for projectile-add-known-project
Thanks!
> Add projectile-add-known-project kbd

- CHANGELOG.md
- projectile.el
Set condition under which `projectile-indexing-method` should be considered "safe" as a dir-local variable: namely that it is one of the symbols `native`, `hybrid`, or `alien`.
Per #1940 
Thanks!
> Set condition for considering `projectile-indexing-method` to be safe

- projectile.el
Otherwise, the globs are interpreted by the shell which may lead to errors such as
zsh:1: no matches found: !*.bundle.js
In this example the command was
/usr/bin/rg [...] --glob !*.bundle.js [...]
and after this change will become
/usr/bin/rg [...] --glob '!*.bundle.js' [...]
Thanks!
> Quote ignore globs in projectile-ripgrep

- projectile.el
In jujutsu users can configure the default behaviour of `jj file list` so that it no longer puts out file names separated by newlines (which is the default behaviour). This means the output of `jj file list` can't be trusted to be stable. On the other hand the same mechanism allows you to output the files separated with a null byte without invoking `tr`, this has the additional benefit that filenames with newlines in them are now working.
Thanks!
> Use template for jujutsu file listing

- projectile.el
More robust cmake-version matching to account for "-dirty" version on arch linux. Closes #1951.
Thanks!
> Make CMake version parsing more robust.

- CHANGELOG.md
- doc/modules/ROOT/pages/usage.adoc
(see title / #1954; should be self-explanatory)
Couple of notes:
- I went ahead to s/setq/customize-set-variable/; figured that was the better way based on what I read online (`projectile-auto-cleanup-known-projects` is a variable that can be customized)
- added a separate commit after seeing CHANGELOG.md mentioned in the PR template. But on second thought.. I'm not sure if this would be a candidate (I'm not really `adding/changing user-visible functionality`?)
> pages/usage.doc: fix ELisp for "Removal of missing projects"; Fixes #1954
